---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: landscape-vector-activation-manager
rules:
- apiGroups:
  - common.konfidence.cloud
  resources:
  - stages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - common.konfidence.cloud
  resources:
  - stages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination
  resources:
  - leases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - activationtaskexecutions
  - activationtaskregistrations
  - stageversions
  - stageversionusages
  - vectoractivations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - activationtaskexecutions/status
  - activationtaskregistrations/status
  - stageversions/status
  - stageversionusages/status
  - vectoractivations/status
  verbs:
  - get
  - patch
  - update
