---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: landscape-vector-activation-manager
rules:
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - activationexecutions
  - vectoractivations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - activationexecutions/status
  - vectoractivations/status
  verbs:
  - get
  - patch
  - update
