apiVersion: v1
kind: Namespace
metadata:
  name: sample-project

---
apiVersion: landscape.konfidence.cloud/v1alpha1
kind: VectorDeployment
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: common.konfidence.cloud.example.vector-0.3.0
  namespace: sample-project
spec:
  vector: https://registry.kdenv.lab/sample-project//github.com/konfidence-project/sample-vector:0.3.0

