apiVersion: landscape.konfidence.cloud/v1alpha1
kind: VectorDeployment
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: common.konfidence.cloud.example.vector-0.0.1
spec:
  vector:  https://konfidence.common.repositories.cloud.sap/ocm-test/ocm/vector//dwc.tools.sap/dwc-project/vector/dev-eu10:0.1.0

