apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: stagesync.konfidence.cloud.export
spec:
  resources:
    - group: global.konfidence.cloud
      name: stagesyncs
      schema: v1a.stagesyncs.global.konfidence.cloud
      storage:
        crd: {}