apiVersion: api.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: stagesync.konfidence.cloud.export
spec:
  resources:
    - group: galaxy.konfidence.cloud
      name: stagesyncs
      schema: v1a.stagesyncs.galaxy.konfidence.cloud
      storage:
        crd: {}
