apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: project-1
spec:
  type:
    name: gcp-workspacetype-konfidence-cloud
    path: root
---
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: project-2
spec:
  type:
    name: gcp-workspacetype-konfidence-cloud
    path: root    
---
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: lcp-1
spec:
  type:
    name: gcp-workspacetype-konfidence-cloud
    path: root