apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: konfidence-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "localhost:5100": {
          "auth": "dXNlcjpwYXNzd29yZA=="
        },
        "localhost:5200": {
          "auth": "dXNlcjpwYXNzd29yZA=="
        }
      }
    }