apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: konfidence-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "localhost:5100": {
          "auth": "dXNlcjp1c2Vy"
        }
      }
    }