{{- if .Values.controller.install -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{- include "konfidence.operatorLabels" . | nindent 4 }}
  name: {{ include "konfidence.fullname" . }}-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - konfidence.cloud
  resources:
  - activationtaskexecutions
  - activationtaskregistrations
  - artifactdeployments
  - landscapes
  - projects
  - stages
  - stageversions
  - stageversionusages
  - taskexecutions
  - vectoractivations
  - vectorassignments
  - vectordeployments
  - vectormigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfidence.cloud
  resources:
  - activationtaskexecutions/status
  - activationtaskregistrations/status
  - artifactdeployments/status
  - deploymenttargets/status
  - landscapes/status
  - projects/status
  - stages/status
  - stageversions/status
  - stageversionusages/status
  - taskexecutions/status
  - vectoractivations/status
  - vectordeployments/status
  - vectormigrations/status
  - vectorpromotionconfigs/status
  - vectorpromotions/status
  - vectortemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - konfidence.cloud
  resources:
  - deploymentclasses
  - deploymenttargets
  - vectorpromotionconfigs
  - vectortemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfidence.cloud
  resources:
  - landscapes/finalizers
  - projects/finalizers
  - vectordeployments/finalizers
  verbs:
  - update
- apiGroups:
  - konfidence.cloud
  resources:
  - vectordata
  - vectorpromotions
  verbs:
  - create
  - delete
  - get
  - list
  - watch
{{- end }}
