---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcp-vector-assembly-manager
rules:
- apiGroups:
  - global.konfidence.cloud
  resources:
  - vectortemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - global.konfidence.cloud
  resources:
  - vectortemplates/status
  verbs:
  - get
  - patch
  - update
