---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: galaxy-vector-assembly-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galaxy.konfidence.cloud
  resources:
  - vectortemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galaxy.konfidence.cloud
  resources:
  - vectortemplates/status
  verbs:
  - get
  - patch
  - update
