apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: galaxy-vector-assembly-controller
    app.kubernetes.io/managed-by: kustomize
  name: galaxy-vector-assembly-controller
