// Code generated by MockGen. DO NOT EDIT.
// Source: ocm_port.go
//
// Generated by this command:
//
//	mockgen -source=ocm_port.go -destination=mock_ocm_port_test.go -package=controller
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	compref "ocm.software/open-component-model/bindings/go/oci/compref"
)

// MockVectorOcmPort is a mock of VectorOcmPort interface.
type MockVectorOcmPort struct {
	ctrl     *gomock.Controller
	recorder *MockVectorOcmPortMockRecorder
	isgomock struct{}
}

// MockVectorOcmPortMockRecorder is the mock recorder for MockVectorOcmPort.
type MockVectorOcmPortMockRecorder struct {
	mock *MockVectorOcmPort
}

// NewMockVectorOcmPort creates a new mock instance.
func NewMockVectorOcmPort(ctrl *gomock.Controller) *MockVectorOcmPort {
	mock := &MockVectorOcmPort{ctrl: ctrl}
	mock.recorder = &MockVectorOcmPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorOcmPort) EXPECT() *MockVectorOcmPortMockRecorder {
	return m.recorder
}

// GetArtifactManifestByReference mocks base method.
func (m *MockVectorOcmPort) GetArtifactManifestByReference(ctx context.Context, ref compref.Ref) (ArtifactManifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifactManifestByReference", ctx, ref)
	ret0, _ := ret[0].(ArtifactManifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifactManifestByReference indicates an expected call of GetArtifactManifestByReference.
func (mr *MockVectorOcmPortMockRecorder) GetArtifactManifestByReference(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifactManifestByReference", reflect.TypeOf((*MockVectorOcmPort)(nil).GetArtifactManifestByReference), ctx, ref)
}

// GetVectorDescriptor mocks base method.
func (m *MockVectorOcmPort) GetVectorDescriptor(ctx context.Context, ref compref.Ref) (VectorDescriptor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVectorDescriptor", ctx, ref)
	ret0, _ := ret[0].(VectorDescriptor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVectorDescriptor indicates an expected call of GetVectorDescriptor.
func (mr *MockVectorOcmPortMockRecorder) GetVectorDescriptor(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVectorDescriptor", reflect.TypeOf((*MockVectorOcmPort)(nil).GetVectorDescriptor), ctx, ref)
}
