apiVersion: landscape.konfidence.cloud/v1alpha1
kind: VectorActivation
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: vectoractivation-sample
spec:
  stageVersion: some-stage-version
  vector: https://registry.kdenv.lab/ocm/vector//common.konfidence.cloud/example/vector:0.0.1
