apiVersion: landscape.konfidence.cloud/v1alpha1
kind: VectorAssignment
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: vectorassignment-sample
spec:
  manifest:
    type: cloud.konfidence.flux.helm
    allowReuse: true
  artifactDeploymentRef:
    name: artifactdeployment-1
  vectorDeploymentRef:
    name: vectordeployment-1