default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: check-added-large-files
  -   repo: https://github.com/compilerla/conventional-pre-commit
      rev: v4.3.0
      hooks:
        - id: conventional-pre-commit
  -   repo: local
      hooks:
        - id: check-generate
          name: make check-generate
          entry: make check-generate
          language: system
          pass_filenames: false
          files: ^(api/v1alpha1/.*\.go|test/data/samples/.*\.yaml|hack/transform-crd-docs\.sh|cmd/kden/.*\.go|internal/kden/.*\.go)$
        - id: validate
          name: make validate
          entry: make validate
          language: system
          pass_filenames: false
          files: ^(test/data/samples/.*\.yaml|api/v1alpha1/.*\.go)$
