apiVersion: global.konfidence.cloud/v1alpha1
kind: StageConfiguration
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: stage-configuration-dev
  namespace: default
spec:
  name: stage-dev
  vector: https://registry.kdenv.lab/sample-project//konfidence-project/constructed-vector
  targetWorkspace: root:project-star
  targetNamespace: dev-eu10
  config:
    - kind: Secret
      apiVersion: v1
      name: registry-credentials
