---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - landscape.konfidence.tools.sap
  resources:
  - artifactdeployments
  - vectorassignments
  - vectordeployments
  - vectordeploymentusages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - landscape.konfidence.tools.sap
  resources:
  - vectordeployments/finalizers
  - vectordeploymentusages/finalizers
  verbs:
  - update
- apiGroups:
  - landscape.konfidence.tools.sap
  resources:
  - vectordeployments/status
  - vectordeploymentusages/status
  verbs:
  - get
  - patch
  - update
