apiVersion: star.konfidence.cloud/v1alpha1
kind: ArtifactDeployment
metadata:
  name: ad09d2fe456d889ea652453f951ed1fdd3dab21edaca7d6a12628d50e782b429
  namespace: default
spec:
  component:
    name: cloud.konfidence.flux.kustomize
    resources:
      - content:
          imageReference: registry.kdenv.lab/podinfo:6.9.1
          type: ociArtifact
        name: sample-service
        type: kustomize
    version: 1.0.0
  manifest:
    allowReuse: true
    type: cloud.konfidence.flux.kustomize
  taskManifests: [ ]
