apiVersion: star.konfidence.cloud/v1alpha1
kind: ActivationTaskExecution
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: activationtaskexecution-sample
spec:
  type: k8s-job
  spec: {
    "template": "refine-me"
  }
  vectorActivation: "activation-1"

