apiVersion: common.konfidence.cloud/v1alpha1
kind: Stage
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: stage-dev
spec:
  vector: https://registry.kdenv.lab/sample-project//github.com/konfidence-project/sample-vector:0.3.0



