server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: debug

authentication_backend:
  file:
    path: /config/users.yml
    password:
      algorithm: 'argon2'
  password_reset:
    disable: true

access_control:
  default_policy: 'one_factor'

session:
  secret: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'
  same_site: 'lax'
  cookies:
    - domain: 'auth.localhost'
      authelia_url: 'https://auth.localhost'
    - domain: 'host.docker.internal'
      authelia_url: 'https://host.docker.internal'

notifier:
  filesystem:
    filename: /dev/null

storage:
  encryption_key: 'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210'
  local:
    path: '/config/db.sqlite3'

identity_providers:
  oidc:
    hmac_secret: '00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff'
    enforce_pkce: always
    jwks:
      - key_id: 'local-key'
        algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/certs/oidc-signing-key.pem" | mindent 10 "|" | msquote }}
        certificate_chain: {{ secret "/certs/oidc-signing-cert.pem" | mindent 10 "|" | msquote }}
    clients:
      - client_id: konfidence
        # Plaintext local development client secret: konfidence
        client_secret: '$pbkdf2-sha512$310000$JBSHpz5iB1DccB18nI/c4A$n8DPKSpu3Mm2DOdNpmlpj./LQF0oupvdQV66HMogwQGJpCz80i8ZBpo6tZ7N2wBW1/bGzY1h12rGuBSMD3ISzQ'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://api.localhost/api/v1/auth/callback
        grant_types:
          - 'authorization_code'
          - 'refresh_token'
        scopes: [openid, profile, email, groups, offline_access]
        token_endpoint_auth_method: 'client_secret_basic'
        response_types:
          - 'code'
