apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: star-galaxy-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: star-galaxy-sync-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: star-galaxy-sync-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: star-galaxy-sync-controller
