apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: star-galaxy-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: star-galaxy-sync-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: star-galaxy-sync-manager
subjects:
  - kind: ServiceAccount
    name: star-galaxy-sync-controller
