apiVersion: v2
name: konfidence
description: >-
  Konfidence operator for orchestrating multi-service deployments (with bundled
  CRDs).
type: application
version: 0.0.1-alpha.1
appVersion: 0.0.1-alpha.1
kubeVersion: '>=1.27.0-0'
keywords:
  - konfidence
  - deployment
  - orchestration
  - controller
  - operator
home: https://github.com/konfidence-project/konfidence
sources:
  - https://github.com/konfidence-project/konfidence
maintainers:
  - name: Konfidence maintainers
