{{- if .Values.controller.install -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{- include "galaxy.labels" . | nindent 4 }}
  name: {{ include "galaxy.fullname" . }}-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - galaxy.konfidence.cloud
  resources:
  - stageconfigurations
  - stagesyncs
  - vectorpromotions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - galaxy.konfidence.cloud
  resources:
  - stageconfigurations/status
  - stagesyncs/status
  - vectorpromotionconfigs/status
  - vectorpromotions/status
  - vectortemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - galaxy.konfidence.cloud
  resources:
  - vectorpromotionconfigs
  - vectortemplates
  verbs:
  - get
  - list
  - watch
{{- end }}
