const HTTP_OK = 200;
const HTTP_FOUND = 302;
const HTTP_SEE_OTHER = 303;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_FORBIDDEN = 403;
const HTTP_NOT_FOUND = 404;
const HTTP_BAD_GATEWAY = 502;
const HTTP_SERVICE_UNAVAILABLE = 503;
const HTTP_MAX_ERROR_STATUS = 599;

export {
  HTTP_BAD_GATEWAY,
  HTTP_BAD_REQUEST,
  HTTP_FORBIDDEN,
  HTTP_FOUND,
  HTTP_MAX_ERROR_STATUS,
  HTTP_NOT_FOUND,
  HTTP_OK,
  HTTP_SEE_OTHER,
  HTTP_SERVICE_UNAVAILABLE,
  HTTP_UNAUTHORIZED,
};
