apiVersion: common.konfidence.tools.sap/v1alpha1
kind: OCMComponentVersionOCI
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: github.tools.sap-example-vector-0.0.1
spec:
  component: github.tools.sap/example/vector
  version: 0.0.1
  repository:
    url: https://registry.kdenv.lab/ocm/vector
