apiVersion: common.konfidence.tools.sap/v1alpha1
kind: Stage
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: stage-dev
spec:
  name: dev
  vector: https://registry.kdenv.lab/ocm/vector//common.konfidence.tools.sap/example/vector:0.0.1



