## Append samples of your project ##
resources:
- common_v1alpha1_stage_dev.yaml
- landscape_v1alpha1_vectordeploymentusage.yaml
- landscape_v1alpha1_vectordeployment.yaml
- landscape_v1alpha1_vectorassignment.yaml
- landscape_v1alpha1_stageversion.yaml
- landscape_v1alpha1_stageversionusage.yaml
- landscape_v1alpha1_vectormigration.yaml
- landscape_v1alpha1_taskexecution.yaml
- landscape_v1alpha1_vectoractivation.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
