apiVersion: landscape.konfidence.tools.sap/v1alpha1
kind: VectorAssignment
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: vectorassignment-sample
spec:
  # TODO(user): Add fields here
