apiVersion: landscape.konfidence.cloud/v1alpha1
kind: TaskExecution
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: taskexecution-sample
spec:
  
