apiVersion: landscape.konfidence.cloud/v1alpha1
kind: VectorDeploymentUsage
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: vectordeploymentusage-stage-dev
spec:
  vector: https://registry.konfidence.cloud/ocm/vector//common.konfidence.cloud/example/vector:0.0.1

