apiVersion: galaxy.konfidence.cloud/v1alpha1
kind: VectorTemplate
metadata:
  namespace: star-dev
  name: shopping-app-latest
spec:
  base: https://registry.kdenv.lab/sample-project//konfidence-project/sample-vector
  uploadTarget: https://registry.kdenv.lab/sample-project//konfidence-project/constructed-vector
  components:
    - name: https://registry.kdenv.lab/sample-project//konfidence-project/sample-vector/service1
    - name: https://registry.kdenv.lab/sample-project//konfidence-project/sample-vector/service1
    - name: https://registry.dwc.com/sample-project//dwc.tools.sap/dwc-project/dev/service2
    - name: https://registry.example.lab/sample-project//dwc.tools.sap/dwc-project/dev/service3
  config:
    - kind: Secret
      apiVersion: v1
      name: registry-credentials
