// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ArtifactDeploymentStatus.
const (
	ArtifactDeployed ArtifactDeploymentStatus = "ArtifactDeployed"
	ArtifactFetched  ArtifactDeploymentStatus = "ArtifactFetched"
)

// Valid indicates whether the value is a known member of the ArtifactDeploymentStatus enum.
func (e ArtifactDeploymentStatus) Valid() bool {
	switch e {
	case ArtifactDeployed:
		return true
	case ArtifactFetched:
		return true
	default:
		return false
	}
}

// Defines values for PromotionSourceReferenceKind.
const (
	PromotionSourceReferenceKindStage          PromotionSourceReferenceKind = "Stage"
	PromotionSourceReferenceKindVectorTemplate PromotionSourceReferenceKind = "VectorTemplate"
)

// Valid indicates whether the value is a known member of the PromotionSourceReferenceKind enum.
func (e PromotionSourceReferenceKind) Valid() bool {
	switch e {
	case PromotionSourceReferenceKindStage:
		return true
	case PromotionSourceReferenceKindVectorTemplate:
		return true
	default:
		return false
	}
}

// Defines values for PromotionTargetReferenceKind.
const (
	PromotionTargetReferenceKindStage PromotionTargetReferenceKind = "Stage"
)

// Valid indicates whether the value is a known member of the PromotionTargetReferenceKind enum.
func (e PromotionTargetReferenceKind) Valid() bool {
	switch e {
	case PromotionTargetReferenceKindStage:
		return true
	default:
		return false
	}
}

// Defines values for StageVersionStatus.
const (
	DeploymentCreated StageVersionStatus = "DeploymentCreated"
)

// Valid indicates whether the value is a known member of the StageVersionStatus enum.
func (e StageVersionStatus) Valid() bool {
	switch e {
	case DeploymentCreated:
		return true
	default:
		return false
	}
}

// Defines values for VectorDeploymentStatus.
const (
	ArtifactDeploymentCreated VectorDeploymentStatus = "ArtifactDeploymentCreated"
	VectorDownloaded          VectorDeploymentStatus = "VectorDownloaded"
)

// Valid indicates whether the value is a known member of the VectorDeploymentStatus enum.
func (e VectorDeploymentStatus) Valid() bool {
	switch e {
	case ArtifactDeploymentCreated:
		return true
	case VectorDownloaded:
		return true
	default:
		return false
	}
}

// Defines values for VectorPromotionStatus.
const (
	Blocked    VectorPromotionStatus = "Blocked"
	Failed     VectorPromotionStatus = "Failed"
	InProgress VectorPromotionStatus = "InProgress"
	Ready      VectorPromotionStatus = "Ready"
	Succeeded  VectorPromotionStatus = "Succeeded"
	Superseded VectorPromotionStatus = "Superseded"
	Waiting    VectorPromotionStatus = "Waiting"
)

// Valid indicates whether the value is a known member of the VectorPromotionStatus enum.
func (e VectorPromotionStatus) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Failed:
		return true
	case InProgress:
		return true
	case Ready:
		return true
	case Succeeded:
		return true
	case Superseded:
		return true
	case Waiting:
		return true
	default:
		return false
	}
}

// ArtifactDeployment defines model for ArtifactDeployment.
type ArtifactDeployment struct {
	Artifact ArtifactReference `json:"artifact"`

	// Id The artifactDeployment id
	Id ArtifactDeploymentId `json:"id"`

	// LandscapeId The landscape id
	LandscapeId LandscapeId `json:"landscapeId"`
	StageIds    []StageId   `json:"stageIds"`

	// Status The artifactDeployment status
	Status              ArtifactDeploymentStatus `json:"status"`
	VectorDeploymentIds []VectorDeploymentId     `json:"vectorDeploymentIds"`
}

// ArtifactDeploymentStatus The artifactDeployment status
type ArtifactDeploymentStatus string

// ArtifactDeploymentId The artifactDeployment id
type ArtifactDeploymentId = string

// ArtifactDeploymentList defines model for ArtifactDeploymentList.
type ArtifactDeploymentList struct {
	Data []ArtifactDeployment `json:"data"`
}

// ArtifactReference defines model for ArtifactReference.
type ArtifactReference = ComponentReference

// ComponentReference defines model for ComponentReference.
type ComponentReference struct {
	ComponentName    string `json:"componentName"`
	ComponentVersion string `json:"componentVersion"`
	Repository       string `json:"repository"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Identity defines model for Identity.
type Identity struct {
	Email        string              `json:"email"`
	FamilyName   string              `json:"familyName"`
	GivenName    string              `json:"givenName"`
	Name         string              `json:"name"`
	ProjectRoles map[string][]string `json:"projectRoles"`
}

// Landscape defines model for Landscape.
type Landscape struct {
	// Id The landscape id
	Id LandscapeId `json:"id"`

	// Name The name of the landscape
	Name string `json:"name"`
}

// LandscapeId The landscape id
type LandscapeId = string

// LandscapeList defines model for LandscapeList.
type LandscapeList struct {
	Data []Landscape `json:"data"`
}

// Project defines model for Project.
type Project struct {
	// Id The project id
	Id ProjectId `json:"id"`

	// Name The name of the project
	Name string `json:"name"`
}

// ProjectId The project id
type ProjectId = string

// ProjectList defines model for ProjectList.
type ProjectList struct {
	Data []Project `json:"data"`
}

// PromotionApproval defines model for PromotionApproval.
type PromotionApproval struct {
	// ApprovedAt Time the approval was granted
	ApprovedAt time.Time `json:"approvedAt"`

	// ApprovedBy Identity that granted the approval
	ApprovedBy string `json:"approvedBy"`
}

// PromotionSourceReference defines model for PromotionSourceReference.
type PromotionSourceReference struct {
	// Kind Promotion source kind
	Kind PromotionSourceReferenceKind `json:"kind"`

	// Landscape Promotion source landscape
	Landscape *string `json:"landscape,omitempty"`

	// Name Promotion source name
	Name string `json:"name"`
}

// PromotionSourceReferenceKind Promotion source kind
type PromotionSourceReferenceKind string

// PromotionTargetReference defines model for PromotionTargetReference.
type PromotionTargetReference struct {
	// Kind Promotion target kind
	Kind PromotionTargetReferenceKind `json:"kind"`

	// Landscape Promotion target landscape
	Landscape string `json:"landscape"`

	// Name Promotion target name
	Name string `json:"name"`
}

// PromotionTargetReferenceKind Promotion target kind
type PromotionTargetReferenceKind string

// Stage defines model for Stage.
type Stage struct {
	// Id The stage id
	Id StageId `json:"id"`

	// LandscapeId The landscape id
	LandscapeId LandscapeId `json:"landscapeId"`

	// Name The stage name
	Name               string       `json:"name"`
	TargetStageVersion StageVersion `json:"targetStageVersion"`
}

// StageId The stage id
type StageId = string

// StageList defines model for StageList.
type StageList struct {
	Data []Stage `json:"data"`
}

// StageVersion defines model for StageVersion.
type StageVersion struct {
	// Active Indicates if this is the latest active stageVersion
	Active bool `json:"active"`

	// Id The stageVersion id
	Id StageVersionId `json:"id"`

	// StageGeneration Generation of the parent stage
	StageGeneration int                `json:"stageGeneration"`
	Status          StageVersionStatus `json:"status"`

	// Vector StageVersion vector
	Vector string `json:"vector"`
}

// StageVersionStatus defines model for StageVersion.Status.
type StageVersionStatus string

// StageVersionId The stageVersion id
type StageVersionId = string

// VectorDeployment defines model for VectorDeployment.
type VectorDeployment struct {
	// Id The vectorDeployment id
	Id VectorDeploymentId `json:"id"`

	// LandscapeId The landscape id
	LandscapeId LandscapeId `json:"landscapeId"`

	// StageId The stage id
	StageId StageId `json:"stageId"`

	// Status The vectorDeployment status
	Status VectorDeploymentStatus `json:"status"`
	Vector VectorReference        `json:"vector"`
}

// VectorDeploymentStatus The vectorDeployment status
type VectorDeploymentStatus string

// VectorDeploymentId The vectorDeployment id
type VectorDeploymentId = string

// VectorDeploymentList defines model for VectorDeploymentList.
type VectorDeploymentList struct {
	Data []VectorDeployment `json:"data"`
}

// VectorPromotion defines model for VectorPromotion.
type VectorPromotion struct {
	Approval *PromotionApproval `json:"approval,omitempty"`

	// Id The vectorPromotion id
	Id               VectorPromotionId        `json:"id"`
	RequireApproval  *bool                    `json:"requireApproval,omitempty"`
	Sequence         *int64                   `json:"sequence,omitempty"`
	Source           PromotionSourceReference `json:"source"`
	Status           *VectorPromotionStatus   `json:"status,omitempty"`
	Target           PromotionTargetReference `json:"target"`
	TtlAfterFinished *string                  `json:"ttlAfterFinished,omitempty"`
	Vector           string                   `json:"vector"`
}

// VectorPromotionStatus defines model for VectorPromotion.Status.
type VectorPromotionStatus string

// VectorPromotionConfig defines model for VectorPromotionConfig.
type VectorPromotionConfig struct {
	// Id The vectorPromotionConfig id
	Id                 VectorPromotionConfigId  `json:"id"`
	KeepLastPromotions *int                     `json:"keepLastPromotions,omitempty"`
	Promotions         []VectorPromotion        `json:"promotions"`
	Source             PromotionSourceReference `json:"source"`
	Target             PromotionTargetReference `json:"target"`
	TtlAfterFinished   *string                  `json:"ttlAfterFinished,omitempty"`
}

// VectorPromotionConfigId The vectorPromotionConfig id
type VectorPromotionConfigId = string

// VectorPromotionConfigList defines model for VectorPromotionConfigList.
type VectorPromotionConfigList struct {
	Data []VectorPromotionConfig `json:"data"`
}

// VectorPromotionId The vectorPromotion id
type VectorPromotionId = string

// VectorReference defines model for VectorReference.
type VectorReference = ComponentReference

// LandscapeQueryId defines model for LandscapeQueryId.
type LandscapeQueryId = string

// ProjectPathId defines model for ProjectPathId.
type ProjectPathId = string

// VectorDeploymentQueryId defines model for VectorDeploymentQueryId.
type VectorDeploymentQueryId = string

// VectorPromotionConfigPathId defines model for VectorPromotionConfigPathId.
type VectorPromotionConfigPathId = string

// VectorPromotionPathId defines model for VectorPromotionPathId.
type VectorPromotionPathId = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// AuthCallbackV1Params defines parameters for AuthCallbackV1.
type AuthCallbackV1Params struct {
	State            string  `form:"state" json:"state"`
	Code             *string `form:"code,omitempty" json:"code,omitempty"`
	Error            *string `form:"error,omitempty" json:"error,omitempty"`
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// PostExchangeCodeV1JSONBody defines parameters for PostExchangeCodeV1.
type PostExchangeCodeV1JSONBody struct {
	Code     string `json:"code"`
	Verifier string `json:"verifier"`
}

// LoginV1Params defines parameters for LoginV1.
type LoginV1Params struct {
	// ReturnUrl Fully qualified URL to redirect to after login. The URL must be present in the API server allowlist.
	ReturnUrl string `form:"return_url" json:"return_url"`

	// CodeChallenge PKCE S256 challenge used for CLI login.
	CodeChallenge *string `form:"code_challenge,omitempty" json:"code_challenge,omitempty"`
}

// ListArtifactDeploymentsV1Params defines parameters for ListArtifactDeploymentsV1.
type ListArtifactDeploymentsV1Params struct {
	// LandscapeId Filter by landscapeId
	LandscapeId *LandscapeQueryId `form:"landscapeId,omitempty" json:"landscapeId,omitempty"`

	// VectorDeploymentId Filter by vectorDeploymentId
	VectorDeploymentId *VectorDeploymentQueryId `form:"vectorDeploymentId,omitempty" json:"vectorDeploymentId,omitempty"`
}

// ListStagesV1Params defines parameters for ListStagesV1.
type ListStagesV1Params struct {
	// LandscapeId Filter by landscapeId
	LandscapeId *LandscapeQueryId `form:"landscapeId,omitempty" json:"landscapeId,omitempty"`
}

// ListVectorDeploymentsV1Params defines parameters for ListVectorDeploymentsV1.
type ListVectorDeploymentsV1Params struct {
	// LandscapeId Filter by landscapeId
	LandscapeId *LandscapeQueryId `form:"landscapeId,omitempty" json:"landscapeId,omitempty"`
}

// PostExchangeCodeV1JSONRequestBody defines body for PostExchangeCodeV1 for application/json ContentType.
type PostExchangeCodeV1JSONRequestBody PostExchangeCodeV1JSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AuthCallbackV1 OIDC callback
	// (GET /v1/auth/callback)
	AuthCallbackV1(w http.ResponseWriter, r *http.Request, params AuthCallbackV1Params)
	// PostExchangeCodeV1 Send temp exchange code and PKCE verifier to get session
	// (POST /v1/exchange)
	PostExchangeCodeV1(w http.ResponseWriter, r *http.Request)
	// GetIdentityV1 Get the current user identity
	// (GET /v1/identity)
	GetIdentityV1(w http.ResponseWriter, r *http.Request)
	// LoginV1 Initiate OIDC login
	// (GET /v1/login)
	LoginV1(w http.ResponseWriter, r *http.Request, params LoginV1Params)
	// LogoutV1 Terminate the current session
	// (POST /v1/logout)
	LogoutV1(w http.ResponseWriter, r *http.Request)
	// ListProjectsV1 List all projects
	// (GET /v1/projects)
	ListProjectsV1(w http.ResponseWriter, r *http.Request)
	// ListArtifactDeploymentsV1 List all artifactDeployments for a project.
	// (GET /v1/projects/{projectId}/artifactDeployments)
	ListArtifactDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListArtifactDeploymentsV1Params)
	// ListLandscapesV1 List all landscapes for a specific project
	// (GET /v1/projects/{projectId}/landscapes)
	ListLandscapesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId)
	// ListStagesV1 List all stages for a project
	// (GET /v1/projects/{projectId}/stages)
	ListStagesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListStagesV1Params)
	// ListVectorDeploymentsV1 List all vectorDeployments for a project
	// (GET /v1/projects/{projectId}/vectorDeployments)
	ListVectorDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListVectorDeploymentsV1Params)
	// ListVectorPromotionConfigsV1 List all vectorPromotionConfigs for a project
	// (GET /v1/projects/{projectId}/vectorPromotionConfigs)
	ListVectorPromotionConfigsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId)
	// GetVectorPromotionConfigV1 Get a single vectorPromotionConfig for a project
	// (GET /v1/projects/{projectId}/vectorPromotionConfigs/{vectorPromotionConfigId})
	GetVectorPromotionConfigV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionConfigId VectorPromotionConfigPathId)
	// GetVectorPromotionV1 Get a single vectorPromotion for a project.
	// (GET /v1/projects/{projectId}/vectorPromotions/{vectorPromotionId})
	GetVectorPromotionV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionId VectorPromotionPathId)
	// ApproveVectorPromotionV1 Approves the given vectorPromotion for the specified project
	// (POST /v1/projects/{projectId}/vectorPromotions/{vectorPromotionId}/approve)
	ApproveVectorPromotionV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionId VectorPromotionPathId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// AuthCallbackV1 OIDC callback
// (GET /v1/auth/callback)
func (_ Unimplemented) AuthCallbackV1(w http.ResponseWriter, r *http.Request, params AuthCallbackV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostExchangeCodeV1 Send temp exchange code and PKCE verifier to get session
// (POST /v1/exchange)
func (_ Unimplemented) PostExchangeCodeV1(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetIdentityV1 Get the current user identity
// (GET /v1/identity)
func (_ Unimplemented) GetIdentityV1(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LoginV1 Initiate OIDC login
// (GET /v1/login)
func (_ Unimplemented) LoginV1(w http.ResponseWriter, r *http.Request, params LoginV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LogoutV1 Terminate the current session
// (POST /v1/logout)
func (_ Unimplemented) LogoutV1(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListProjectsV1 List all projects
// (GET /v1/projects)
func (_ Unimplemented) ListProjectsV1(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListArtifactDeploymentsV1 List all artifactDeployments for a project.
// (GET /v1/projects/{projectId}/artifactDeployments)
func (_ Unimplemented) ListArtifactDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListArtifactDeploymentsV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListLandscapesV1 List all landscapes for a specific project
// (GET /v1/projects/{projectId}/landscapes)
func (_ Unimplemented) ListLandscapesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListStagesV1 List all stages for a project
// (GET /v1/projects/{projectId}/stages)
func (_ Unimplemented) ListStagesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListStagesV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListVectorDeploymentsV1 List all vectorDeployments for a project
// (GET /v1/projects/{projectId}/vectorDeployments)
func (_ Unimplemented) ListVectorDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListVectorDeploymentsV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListVectorPromotionConfigsV1 List all vectorPromotionConfigs for a project
// (GET /v1/projects/{projectId}/vectorPromotionConfigs)
func (_ Unimplemented) ListVectorPromotionConfigsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVectorPromotionConfigV1 Get a single vectorPromotionConfig for a project
// (GET /v1/projects/{projectId}/vectorPromotionConfigs/{vectorPromotionConfigId})
func (_ Unimplemented) GetVectorPromotionConfigV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionConfigId VectorPromotionConfigPathId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetVectorPromotionV1 Get a single vectorPromotion for a project.
// (GET /v1/projects/{projectId}/vectorPromotions/{vectorPromotionId})
func (_ Unimplemented) GetVectorPromotionV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionId VectorPromotionPathId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApproveVectorPromotionV1 Approves the given vectorPromotion for the specified project
// (POST /v1/projects/{projectId}/vectorPromotions/{vectorPromotionId}/approve)
func (_ Unimplemented) ApproveVectorPromotionV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionId VectorPromotionPathId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthCallbackV1 operation middleware
func (siw *ServerInterfaceWrapper) AuthCallbackV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthCallbackV1Params

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error_description"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthCallbackV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostExchangeCodeV1 operation middleware
func (siw *ServerInterfaceWrapper) PostExchangeCodeV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostExchangeCodeV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIdentityV1 operation middleware
func (siw *ServerInterfaceWrapper) GetIdentityV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIdentityV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginV1 operation middleware
func (siw *ServerInterfaceWrapper) LoginV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginV1Params

	// ------------- Required query parameter "return_url" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "return_url", r.URL.Query(), &params.ReturnUrl, runtime.BindQueryParameterOptions{Type: "string", Format: "uri"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "return_url"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "return_url", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "code_challenge" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code_challenge", r.URL.Query(), &params.CodeChallenge, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code_challenge"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutV1 operation middleware
func (siw *ServerInterfaceWrapper) LogoutV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectsV1 operation middleware
func (siw *ServerInterfaceWrapper) ListProjectsV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectsV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArtifactDeploymentsV1 operation middleware
func (siw *ServerInterfaceWrapper) ListArtifactDeploymentsV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArtifactDeploymentsV1Params

	// ------------- Optional query parameter "landscapeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "landscapeId", r.URL.Query(), &params.LandscapeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "landscapeId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "landscapeId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "vectorDeploymentId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "vectorDeploymentId", r.URL.Query(), &params.VectorDeploymentId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "vectorDeploymentId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vectorDeploymentId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArtifactDeploymentsV1(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLandscapesV1 operation middleware
func (siw *ServerInterfaceWrapper) ListLandscapesV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLandscapesV1(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStagesV1 operation middleware
func (siw *ServerInterfaceWrapper) ListStagesV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStagesV1Params

	// ------------- Optional query parameter "landscapeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "landscapeId", r.URL.Query(), &params.LandscapeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "landscapeId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "landscapeId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStagesV1(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVectorDeploymentsV1 operation middleware
func (siw *ServerInterfaceWrapper) ListVectorDeploymentsV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVectorDeploymentsV1Params

	// ------------- Optional query parameter "landscapeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "landscapeId", r.URL.Query(), &params.LandscapeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "landscapeId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "landscapeId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVectorDeploymentsV1(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVectorPromotionConfigsV1 operation middleware
func (siw *ServerInterfaceWrapper) ListVectorPromotionConfigsV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVectorPromotionConfigsV1(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVectorPromotionConfigV1 operation middleware
func (siw *ServerInterfaceWrapper) GetVectorPromotionConfigV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "vectorPromotionConfigId" -------------
	var vectorPromotionConfigId VectorPromotionConfigPathId

	err = runtime.BindStyledParameterWithOptions("simple", "vectorPromotionConfigId", chi.URLParam(r, "vectorPromotionConfigId"), &vectorPromotionConfigId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vectorPromotionConfigId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVectorPromotionConfigV1(w, r, projectId, vectorPromotionConfigId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVectorPromotionV1 operation middleware
func (siw *ServerInterfaceWrapper) GetVectorPromotionV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "vectorPromotionId" -------------
	var vectorPromotionId VectorPromotionPathId

	err = runtime.BindStyledParameterWithOptions("simple", "vectorPromotionId", chi.URLParam(r, "vectorPromotionId"), &vectorPromotionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vectorPromotionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVectorPromotionV1(w, r, projectId, vectorPromotionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveVectorPromotionV1 operation middleware
func (siw *ServerInterfaceWrapper) ApproveVectorPromotionV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "vectorPromotionId" -------------
	var vectorPromotionId VectorPromotionPathId

	err = runtime.BindStyledParameterWithOptions("simple", "vectorPromotionId", chi.URLParam(r, "vectorPromotionId"), &vectorPromotionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vectorPromotionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveVectorPromotionV1(w, r, projectId, vectorPromotionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/login", wrapper.LoginV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/auth/callback", wrapper.AuthCallbackV1)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/logout", wrapper.LogoutV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identity", wrapper.GetIdentityV1)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/exchange", wrapper.PostExchangeCodeV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects", wrapper.ListProjectsV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/landscapes", wrapper.ListLandscapesV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/stages", wrapper.ListStagesV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/vectorDeployments", wrapper.ListVectorDeploymentsV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/vectorPromotionConfigs", wrapper.ListVectorPromotionConfigsV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/vectorPromotionConfigs/{vectorPromotionConfigId}", wrapper.GetVectorPromotionConfigV1)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/projects/{projectId}/vectorPromotions/{vectorPromotionId}/approve", wrapper.ApproveVectorPromotionV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/vectorPromotions/{vectorPromotionId}", wrapper.GetVectorPromotionV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/artifactDeployments", wrapper.ListArtifactDeploymentsV1)
	})

	return r
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type AuthCallbackV1RequestObject struct {
	Params AuthCallbackV1Params
}

type AuthCallbackV1ResponseObject interface {
	VisitAuthCallbackV1Response(w http.ResponseWriter) error
}

type AuthCallbackV1302ResponseHeaders struct {
	Location  *string
	SetCookie *string
}

type AuthCallbackV1302Response struct {
	Headers AuthCallbackV1302ResponseHeaders
}

func (response AuthCallbackV1302Response) VisitAuthCallbackV1Response(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(302)
	return nil
}

type AuthCallbackV1400JSONResponse struct{ BadRequestJSONResponse }

func (response AuthCallbackV1400JSONResponse) VisitAuthCallbackV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AuthCallbackV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AuthCallbackV1401JSONResponse) VisitAuthCallbackV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthCallbackV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response AuthCallbackV1500JSONResponse) VisitAuthCallbackV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostExchangeCodeV1RequestObject struct {
	Body *PostExchangeCodeV1JSONRequestBody
}

type PostExchangeCodeV1ResponseObject interface {
	VisitPostExchangeCodeV1Response(w http.ResponseWriter) error
}

type PostExchangeCodeV1200ResponseHeaders struct {
	SetCookie *string
}

type PostExchangeCodeV1200Response struct {
	Headers PostExchangeCodeV1200ResponseHeaders
}

func (response PostExchangeCodeV1200Response) VisitPostExchangeCodeV1Response(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	return nil
}

type PostExchangeCodeV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostExchangeCodeV1401JSONResponse) VisitPostExchangeCodeV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostExchangeCodeV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response PostExchangeCodeV1500JSONResponse) VisitPostExchangeCodeV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetIdentityV1RequestObject struct {
}

type GetIdentityV1ResponseObject interface {
	VisitGetIdentityV1Response(w http.ResponseWriter) error
}

type GetIdentityV1200JSONResponse Identity

func (response GetIdentityV1200JSONResponse) VisitGetIdentityV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetIdentityV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetIdentityV1401JSONResponse) VisitGetIdentityV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetIdentityV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetIdentityV1500JSONResponse) VisitGetIdentityV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LoginV1RequestObject struct {
	Params LoginV1Params
}

type LoginV1ResponseObject interface {
	VisitLoginV1Response(w http.ResponseWriter) error
}

type LoginV1302ResponseHeaders struct {
	Location  *string
	SetCookie *string
}

type LoginV1302Response struct {
	Headers LoginV1302ResponseHeaders
}

func (response LoginV1302Response) VisitLoginV1Response(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(302)
	return nil
}

type LoginV1400JSONResponse struct{ BadRequestJSONResponse }

func (response LoginV1400JSONResponse) VisitLoginV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LoginV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response LoginV1500JSONResponse) VisitLoginV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutV1RequestObject struct {
}

type LogoutV1ResponseObject interface {
	VisitLogoutV1Response(w http.ResponseWriter) error
}

type LogoutV1200ResponseHeaders struct {
	SetCookie *string
}

type LogoutV1200Response struct {
	Headers LogoutV1200ResponseHeaders
}

func (response LogoutV1200Response) VisitLogoutV1Response(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	return nil
}

type LogoutV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response LogoutV1401JSONResponse) VisitLogoutV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsV1RequestObject struct {
}

type ListProjectsV1ResponseObject interface {
	VisitListProjectsV1Response(w http.ResponseWriter) error
}

type ListProjectsV1200JSONResponse ProjectList

func (response ListProjectsV1200JSONResponse) VisitListProjectsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListProjectsV1401JSONResponse) VisitListProjectsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListProjectsV1500JSONResponse) VisitListProjectsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListArtifactDeploymentsV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
	Params    ListArtifactDeploymentsV1Params
}

type ListArtifactDeploymentsV1ResponseObject interface {
	VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error
}

type ListArtifactDeploymentsV1200JSONResponse ArtifactDeploymentList

func (response ListArtifactDeploymentsV1200JSONResponse) VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListArtifactDeploymentsV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListArtifactDeploymentsV1401JSONResponse) VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListArtifactDeploymentsV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListArtifactDeploymentsV1403JSONResponse) VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListArtifactDeploymentsV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListArtifactDeploymentsV1500JSONResponse) VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
}

type ListLandscapesV1ResponseObject interface {
	VisitListLandscapesV1Response(w http.ResponseWriter) error
}

type ListLandscapesV1200JSONResponse LandscapeList

func (response ListLandscapesV1200JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListLandscapesV1401JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListLandscapesV1403JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1404JSONResponse struct{ NotFoundJSONResponse }

func (response ListLandscapesV1404JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListLandscapesV1500JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListStagesV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
	Params    ListStagesV1Params
}

type ListStagesV1ResponseObject interface {
	VisitListStagesV1Response(w http.ResponseWriter) error
}

type ListStagesV1200JSONResponse StageList

func (response ListStagesV1200JSONResponse) VisitListStagesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStagesV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListStagesV1401JSONResponse) VisitListStagesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListStagesV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListStagesV1403JSONResponse) VisitListStagesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListStagesV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListStagesV1500JSONResponse) VisitListStagesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorDeploymentsV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
	Params    ListVectorDeploymentsV1Params
}

type ListVectorDeploymentsV1ResponseObject interface {
	VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error
}

type ListVectorDeploymentsV1200JSONResponse VectorDeploymentList

func (response ListVectorDeploymentsV1200JSONResponse) VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorDeploymentsV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListVectorDeploymentsV1401JSONResponse) VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorDeploymentsV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListVectorDeploymentsV1403JSONResponse) VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorDeploymentsV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListVectorDeploymentsV1500JSONResponse) VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorPromotionConfigsV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
}

type ListVectorPromotionConfigsV1ResponseObject interface {
	VisitListVectorPromotionConfigsV1Response(w http.ResponseWriter) error
}

type ListVectorPromotionConfigsV1200JSONResponse VectorPromotionConfigList

func (response ListVectorPromotionConfigsV1200JSONResponse) VisitListVectorPromotionConfigsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorPromotionConfigsV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListVectorPromotionConfigsV1401JSONResponse) VisitListVectorPromotionConfigsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorPromotionConfigsV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListVectorPromotionConfigsV1403JSONResponse) VisitListVectorPromotionConfigsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorPromotionConfigsV1404JSONResponse struct{ NotFoundJSONResponse }

func (response ListVectorPromotionConfigsV1404JSONResponse) VisitListVectorPromotionConfigsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorPromotionConfigsV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListVectorPromotionConfigsV1500JSONResponse) VisitListVectorPromotionConfigsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionConfigV1RequestObject struct {
	ProjectId               ProjectPathId               `json:"projectId"`
	VectorPromotionConfigId VectorPromotionConfigPathId `json:"vectorPromotionConfigId"`
}

type GetVectorPromotionConfigV1ResponseObject interface {
	VisitGetVectorPromotionConfigV1Response(w http.ResponseWriter) error
}

type GetVectorPromotionConfigV1200JSONResponse VectorPromotionConfig

func (response GetVectorPromotionConfigV1200JSONResponse) VisitGetVectorPromotionConfigV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionConfigV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetVectorPromotionConfigV1401JSONResponse) VisitGetVectorPromotionConfigV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionConfigV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetVectorPromotionConfigV1403JSONResponse) VisitGetVectorPromotionConfigV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionConfigV1404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVectorPromotionConfigV1404JSONResponse) VisitGetVectorPromotionConfigV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionConfigV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetVectorPromotionConfigV1500JSONResponse) VisitGetVectorPromotionConfigV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionV1RequestObject struct {
	ProjectId         ProjectPathId         `json:"projectId"`
	VectorPromotionId VectorPromotionPathId `json:"vectorPromotionId"`
}

type GetVectorPromotionV1ResponseObject interface {
	VisitGetVectorPromotionV1Response(w http.ResponseWriter) error
}

type GetVectorPromotionV1200JSONResponse VectorPromotion

func (response GetVectorPromotionV1200JSONResponse) VisitGetVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetVectorPromotionV1401JSONResponse) VisitGetVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetVectorPromotionV1403JSONResponse) VisitGetVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionV1404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVectorPromotionV1404JSONResponse) VisitGetVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVectorPromotionV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetVectorPromotionV1500JSONResponse) VisitGetVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ApproveVectorPromotionV1RequestObject struct {
	ProjectId         ProjectPathId         `json:"projectId"`
	VectorPromotionId VectorPromotionPathId `json:"vectorPromotionId"`
}

type ApproveVectorPromotionV1ResponseObject interface {
	VisitApproveVectorPromotionV1Response(w http.ResponseWriter) error
}

type ApproveVectorPromotionV1204Response struct {
}

func (response ApproveVectorPromotionV1204Response) VisitApproveVectorPromotionV1Response(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ApproveVectorPromotionV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ApproveVectorPromotionV1401JSONResponse) VisitApproveVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApproveVectorPromotionV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ApproveVectorPromotionV1403JSONResponse) VisitApproveVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ApproveVectorPromotionV1404JSONResponse struct{ NotFoundJSONResponse }

func (response ApproveVectorPromotionV1404JSONResponse) VisitApproveVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ApproveVectorPromotionV1409JSONResponse struct{ ConflictJSONResponse }

func (response ApproveVectorPromotionV1409JSONResponse) VisitApproveVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ApproveVectorPromotionV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ApproveVectorPromotionV1500JSONResponse) VisitApproveVectorPromotionV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// AuthCallbackV1 OIDC callback
	// (GET /v1/auth/callback)
	AuthCallbackV1(ctx context.Context, request AuthCallbackV1RequestObject) (AuthCallbackV1ResponseObject, error)
	// PostExchangeCodeV1 Send temp exchange code and PKCE verifier to get session
	// (POST /v1/exchange)
	PostExchangeCodeV1(ctx context.Context, request PostExchangeCodeV1RequestObject) (PostExchangeCodeV1ResponseObject, error)
	// GetIdentityV1 Get the current user identity
	// (GET /v1/identity)
	GetIdentityV1(ctx context.Context, request GetIdentityV1RequestObject) (GetIdentityV1ResponseObject, error)
	// LoginV1 Initiate OIDC login
	// (GET /v1/login)
	LoginV1(ctx context.Context, request LoginV1RequestObject) (LoginV1ResponseObject, error)
	// LogoutV1 Terminate the current session
	// (POST /v1/logout)
	LogoutV1(ctx context.Context, request LogoutV1RequestObject) (LogoutV1ResponseObject, error)
	// ListProjectsV1 List all projects
	// (GET /v1/projects)
	ListProjectsV1(ctx context.Context, request ListProjectsV1RequestObject) (ListProjectsV1ResponseObject, error)
	// ListArtifactDeploymentsV1 List all artifactDeployments for a project.
	// (GET /v1/projects/{projectId}/artifactDeployments)
	ListArtifactDeploymentsV1(ctx context.Context, request ListArtifactDeploymentsV1RequestObject) (ListArtifactDeploymentsV1ResponseObject, error)
	// ListLandscapesV1 List all landscapes for a specific project
	// (GET /v1/projects/{projectId}/landscapes)
	ListLandscapesV1(ctx context.Context, request ListLandscapesV1RequestObject) (ListLandscapesV1ResponseObject, error)
	// ListStagesV1 List all stages for a project
	// (GET /v1/projects/{projectId}/stages)
	ListStagesV1(ctx context.Context, request ListStagesV1RequestObject) (ListStagesV1ResponseObject, error)
	// ListVectorDeploymentsV1 List all vectorDeployments for a project
	// (GET /v1/projects/{projectId}/vectorDeployments)
	ListVectorDeploymentsV1(ctx context.Context, request ListVectorDeploymentsV1RequestObject) (ListVectorDeploymentsV1ResponseObject, error)
	// ListVectorPromotionConfigsV1 List all vectorPromotionConfigs for a project
	// (GET /v1/projects/{projectId}/vectorPromotionConfigs)
	ListVectorPromotionConfigsV1(ctx context.Context, request ListVectorPromotionConfigsV1RequestObject) (ListVectorPromotionConfigsV1ResponseObject, error)
	// GetVectorPromotionConfigV1 Get a single vectorPromotionConfig for a project
	// (GET /v1/projects/{projectId}/vectorPromotionConfigs/{vectorPromotionConfigId})
	GetVectorPromotionConfigV1(ctx context.Context, request GetVectorPromotionConfigV1RequestObject) (GetVectorPromotionConfigV1ResponseObject, error)
	// GetVectorPromotionV1 Get a single vectorPromotion for a project.
	// (GET /v1/projects/{projectId}/vectorPromotions/{vectorPromotionId})
	GetVectorPromotionV1(ctx context.Context, request GetVectorPromotionV1RequestObject) (GetVectorPromotionV1ResponseObject, error)
	// ApproveVectorPromotionV1 Approves the given vectorPromotion for the specified project
	// (POST /v1/projects/{projectId}/vectorPromotions/{vectorPromotionId}/approve)
	ApproveVectorPromotionV1(ctx context.Context, request ApproveVectorPromotionV1RequestObject) (ApproveVectorPromotionV1ResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AuthCallbackV1 operation middleware
func (sh *strictHandler) AuthCallbackV1(w http.ResponseWriter, r *http.Request, params AuthCallbackV1Params) {
	var request AuthCallbackV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthCallbackV1(ctx, request.(AuthCallbackV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthCallbackV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthCallbackV1ResponseObject); ok {
		if err := validResponse.VisitAuthCallbackV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostExchangeCodeV1 operation middleware
func (sh *strictHandler) PostExchangeCodeV1(w http.ResponseWriter, r *http.Request) {
	var request PostExchangeCodeV1RequestObject

	var body PostExchangeCodeV1JSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostExchangeCodeV1(ctx, request.(PostExchangeCodeV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostExchangeCodeV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostExchangeCodeV1ResponseObject); ok {
		if err := validResponse.VisitPostExchangeCodeV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIdentityV1 operation middleware
func (sh *strictHandler) GetIdentityV1(w http.ResponseWriter, r *http.Request) {
	var request GetIdentityV1RequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIdentityV1(ctx, request.(GetIdentityV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIdentityV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIdentityV1ResponseObject); ok {
		if err := validResponse.VisitGetIdentityV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginV1 operation middleware
func (sh *strictHandler) LoginV1(w http.ResponseWriter, r *http.Request, params LoginV1Params) {
	var request LoginV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginV1(ctx, request.(LoginV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginV1ResponseObject); ok {
		if err := validResponse.VisitLoginV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutV1 operation middleware
func (sh *strictHandler) LogoutV1(w http.ResponseWriter, r *http.Request) {
	var request LogoutV1RequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutV1(ctx, request.(LogoutV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutV1ResponseObject); ok {
		if err := validResponse.VisitLogoutV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProjectsV1 operation middleware
func (sh *strictHandler) ListProjectsV1(w http.ResponseWriter, r *http.Request) {
	var request ListProjectsV1RequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjectsV1(ctx, request.(ListProjectsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjectsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProjectsV1ResponseObject); ok {
		if err := validResponse.VisitListProjectsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListArtifactDeploymentsV1 operation middleware
func (sh *strictHandler) ListArtifactDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListArtifactDeploymentsV1Params) {
	var request ListArtifactDeploymentsV1RequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListArtifactDeploymentsV1(ctx, request.(ListArtifactDeploymentsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListArtifactDeploymentsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListArtifactDeploymentsV1ResponseObject); ok {
		if err := validResponse.VisitListArtifactDeploymentsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLandscapesV1 operation middleware
func (sh *strictHandler) ListLandscapesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId) {
	var request ListLandscapesV1RequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLandscapesV1(ctx, request.(ListLandscapesV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLandscapesV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLandscapesV1ResponseObject); ok {
		if err := validResponse.VisitListLandscapesV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListStagesV1 operation middleware
func (sh *strictHandler) ListStagesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListStagesV1Params) {
	var request ListStagesV1RequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListStagesV1(ctx, request.(ListStagesV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStagesV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListStagesV1ResponseObject); ok {
		if err := validResponse.VisitListStagesV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVectorDeploymentsV1 operation middleware
func (sh *strictHandler) ListVectorDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListVectorDeploymentsV1Params) {
	var request ListVectorDeploymentsV1RequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVectorDeploymentsV1(ctx, request.(ListVectorDeploymentsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVectorDeploymentsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVectorDeploymentsV1ResponseObject); ok {
		if err := validResponse.VisitListVectorDeploymentsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVectorPromotionConfigsV1 operation middleware
func (sh *strictHandler) ListVectorPromotionConfigsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId) {
	var request ListVectorPromotionConfigsV1RequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVectorPromotionConfigsV1(ctx, request.(ListVectorPromotionConfigsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVectorPromotionConfigsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVectorPromotionConfigsV1ResponseObject); ok {
		if err := validResponse.VisitListVectorPromotionConfigsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVectorPromotionConfigV1 operation middleware
func (sh *strictHandler) GetVectorPromotionConfigV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionConfigId VectorPromotionConfigPathId) {
	var request GetVectorPromotionConfigV1RequestObject

	request.ProjectId = projectId
	request.VectorPromotionConfigId = vectorPromotionConfigId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVectorPromotionConfigV1(ctx, request.(GetVectorPromotionConfigV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVectorPromotionConfigV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVectorPromotionConfigV1ResponseObject); ok {
		if err := validResponse.VisitGetVectorPromotionConfigV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVectorPromotionV1 operation middleware
func (sh *strictHandler) GetVectorPromotionV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionId VectorPromotionPathId) {
	var request GetVectorPromotionV1RequestObject

	request.ProjectId = projectId
	request.VectorPromotionId = vectorPromotionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVectorPromotionV1(ctx, request.(GetVectorPromotionV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVectorPromotionV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVectorPromotionV1ResponseObject); ok {
		if err := validResponse.VisitGetVectorPromotionV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApproveVectorPromotionV1 operation middleware
func (sh *strictHandler) ApproveVectorPromotionV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, vectorPromotionId VectorPromotionPathId) {
	var request ApproveVectorPromotionV1RequestObject

	request.ProjectId = projectId
	request.VectorPromotionId = vectorPromotionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApproveVectorPromotionV1(ctx, request.(ApproveVectorPromotionV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApproveVectorPromotionV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApproveVectorPromotionV1ResponseObject); ok {
		if err := validResponse.VisitApproveVectorPromotionV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fxbc9u2tv4rGJ7z0M4wkpO4nVO9OUqTo4mn0bbT7IdsTwcmlyTUIMAAoB1tj/77HlwI3kCRshUn0+63",
	"WMRlXb51AdZC7qOEZzlnwJSMZvdRjgXOQIEwf51jlsoE5/CPAsR2kerfUpCJILkinEWz6A2hCgS63iJa",
	"jl2kURwR/fGznhXFEcMZRLOoOUImG8iwXlFtc/1ZKkHYOtrt4mgp+J+QqCVWm9Cm7jOqdsqx2lQb5fa7",
	"+Szgc0EEpNFMiQL2b/sREsXFa8gp32bA1Aiub1tTepkPDhwmZil4xvWuc85WZN0nkeDgXvnchkY/UFp+",
	"lZGkjSXqQHJ2erDMOZNgkPsKpxfwuQCp9F8JZwqY+SfOc0oSrLeY/ik1hfe1Zf9XwCqaRf8zraxiar/K",
	"6a9CcHHhNrFbNjldsFtMSYqE3RhVtjSJdnGkxUxJ8oQEfdiAJyZxu0t0R9QGqQ2gpBACmEJSYQWIr8yP",
	"AiQvRAKG5DdcXJM0BfZ0NJ8lCUiJGFcIU8rvIDWULJgCwTA185+QGoYKBl9ySBSkSIK4BYFAz0I8MfKz",
	"5P3G1RtesPSb6BZSrzV0h63sVpoaQ9rvDBdqwwX5NzwheWeF2gBTbnVUGjLiAkmQUv8GX3Ji5bcrLduY",
	"7plQZIUTVflKE5gEz0EoYs0buzFDdJZrXcAKBLAEtERIOnZaw13v4kYEG1jivDZU86fwGhapIZ4oyOTQ",
	"/Es7Qc/NCDsHtlabaPY8Lj0fFgJv3cqqkF2/qwGCO3wgNzyOgBVZNPvkxf0GVLIB7XWb3EMaXcVtfxsH",
	"4tl43j52Y+EAm7t6LPikNRi30okQPTWxxxVkvMgqtvi1zhc0EUHNj5WtIasjqe6S50QGMJ1ihUeLMGAk",
	"uwGhmfX38VwZibYwSt+votmn/WTMy59qBnZlYl3n9w6/frnfTAJw35WcH/ERhCTWP3UGCci5JIqLbThN",
	"qYugNjZu7R/YLSSrpuPr8ARleGqzmoY5zEBKvIZhys0K1fguaa3xlpAQB4tU+2W1DRCfYUKDZK5wRui2",
	"V09rcgus9yvr++DS9AtOnVNPU6INDNNlgy5vEJ0V2r5wv0yY1XNFbYOx2PHfoiskQu/buzIkhwaGUjpd",
	"B6O/lFmZ93VdBxNyjWbRvZT3eTW/UY8z8wscwYdVYnyw63InwYfoYekPiaO14IDxSB1UGwc3dJv0yN9N",
	"PoL0S9E9Rvb2qHaW54LfYhpI08wXSM9UgFeSgZEqdtNN7roWmCmThay4yLCKZpoAeKZIBiF5lDu82nZ3",
	"KD0dUhusypUbWw5qsrZ8XOdmrzwuTSq+J/LdEBa+1XBHZJfLm2FVomYywqg8d3+ALKdYQTA5o3UHNbDL",
	"HtfSZxedNZxn3S9Lx84+u7CrfsBiDeoR8lNmgbD8Hiwut+ijxOXWOFhcdRJDorOsPcAJ1k4ZDz/b9DtP",
	"k373sBtHVhqGhFqCN0huObbf67bPBoGNeqXY55YtK2GnbCYewSVbNT7YIbcl2fLFiSK3AT0tWKpP6SAR",
	"0VGOSESkyzkUSIXsPMt/ubjf/JpzCpiNO1XX6audit8CA4GVI7pJXPXNx2Bc3lmta6AiTMEaRPM8XBp+",
	"dUaaC8Bq74G2S0KdanfdOy4B8GPbXMalLvaeRFvS6gdlSVsYm+2z9kO8RPi8/ujLkAOc075LjvbJv3vF",
	"4ejnd4xynAbuOMZjY1hMtZPw8K1FKYkmWvogEdDDOImMg8YRPFgHbQ92Zq2yQV9uabPOgTy3laaOclYf",
	"O+WIivJ6wtt1hBI+F2Xe4pNYwtTPp2F/ZVKo0Vy0k8ugx/snJkorOY4uAKc6d12wpeBrAVLbxSvKkxtj",
	"BpdFkgBYk3iDCXU/5iCk+fWqN2yPJridzekVFD1bKRBvCCNyY6+l99jcCF/rhOiJ89NHQMuWvx7uF7t1",
	"tF0c3QDk51gq/7F+gVHTft74foCNVZYRuAd5PKaeRMnjNFkT0Wht7veM7TrpPvfYGns0H9mG37Ec5UjO",
	"9/J8tItg4w2TQhC1vdQDrbRcAWjO+Q0xW5hqcGL/9PXgmxTYMze0IhXn5B1sbcWJsBXvMvv/Hz4s0Ror",
	"uMNbdA3qDoCh+fli+vsCJZRoqhFm9h7gnZZ9qqlF84vXcvIvsxNRVG9V+3i2XBiX4lLr6Pa5FhbPgeGc",
	"RLPo5eRk8lJDFauNYXF6+3yKC7WZJpjSa5zc6B+dQTXJvYAEyC3YlLus1NmMN+EpoJXgmfm2eL1EWBsU",
	"koWpka4KiihfEzZBv35JNpit3Sp2HhdI8RtglluQCl9TbYgSYV+CszK3bGs84xJBpn43d7R/fG5YqxpD",
	"Pt0HWxxMHfmwJoLwQu6y++B59tL7oRP/qCtm3yJXrV6DlycvQnpNiYBEIcXLK6ey1tpVI25USydRHG0A",
	"p2UTDk96Tkd+j0LQgW6SS1DPKoNrLjPnTGHCLHhKaCxeT/YuqRc9PTnpc3ZeQNNaJ4aZ8nx4SqNkvYuj",
	"n8bs0+wQqLueaPbpKo5kkWVYbKNZ9H7xeo68YepIs5bmsq9Qm8g4LW2+4GzKeHsuA6b7EVOSmpOzsTht",
	"ZrcgyIqAMH8IUIVg0ouUrJBpEJl0rG3JpSpteM5TMBbnqvuveLo9qG4/svRUkjq69uQnBIpPu7bVt/tx",
	"XlgVto7WZSeAd05pC/sHw9ZKdwi23x6Dl6BDEGQ5KnFWgWj5bv5rhSTF0RoUqkXCIFxJrazXE2gsGsuB",
	"KKGYZNIGChd7nA8yrS5muy5U34Iq79UdSrtaPkqLia9TBrpL3r97cl/iNfcWVKN7qpAgvFB71WMC9R7d",
	"WEdusXwt+J20mveBv5EYAEtzTpiK0TWsCWOErc1IAxw9FK0ov5ug96w/yPilhd9bu0O96RTnpJPAhJKE",
	"c81UKDtodUsWlG7R5wJTjegU/X5xrrcRtQhpI6LLZnS6qsdkhVToGlAuQJpbDEv02XJRdmKZDjFKpJr0",
	"dF1aF/yHjY/9eYk/pheChC73Ojf6WtCXL376GSUbTClo8y0kpMaY5ucLx0kPUdrQ//ATG+4qw198D8yL",
	"/2v0xJy+jB+fifRj6TtJOtAPnNEtkqDQ3QYYMrGaSJQSia8ppD9+lazkyM59wYgiWIGl3pr+HsfAC9Wf",
	"ZMwpYNGUksva0YXFs07w/S19n9s+N9v0euxwXFYgMsJsPPB+hG4PiNEXkPHycNMi/2uE6Yaj/lBS32x2",
	"HYijrvwuB+MophSVjehl+6VEt0SSawo+628EVR0qAqoh5prI7Pp1Q2q9eeA7i6qaJiNSL/9KQf6njpKm",
	"977VfzftNuSNU2JgXk2h2qPjkqoJmmOmQ9LKPACAtPHwAXHRuXoPq7tbfZChMBoSZzVk2nwloaPUwITO",
	"c44Rc/reRHRizzGB2tMyeVzMnp68HJ5UdcAfFeUhzDWRdjj+PQ7Hwb6CbR/Yg9D1GDoCYr8mhJqNat8a",
	"Oacnp8Mz/COCo0KtgoVTr8whISuS1NvZDkOaqVqOQ5ltm3iQOw3jzxSFv5G3/Jp4rXpI/jpezuKkqfPD",
	"0dYOqeOA15l1TBC2g+JfEI/B5oC/DjS78DgKSltVvUOg2p56WFgOFhW/8xDdX2D9G4frHjB8FXRO73te",
	"Au+GcdtTSvcPEQcw+xbCkH0KR7rvZfXTA/5vCPa3oHQeStia9rVkHBfvXaSPw3iYxEeA/BvA+xsA+7+Q",
	"buLlsSf7MWieutcp/TfJbwU2vS/lcxtLVZtW81Zmg+2lcjl0jRVMkG17JGxtvlEBON0+Kx/FoLxqLTJF",
	"xiznGliNSviLk9MJKs3r9OQXe8fvnlZVs6VvQIzRyrWPxYiL8hm5RIx74oLdK5ao79n4Tof/p4z6nTsq",
	"5Tz5ns3o9OSX4Qn+/8E4ht05TdsKg3nZGbQ+U3+w9x4WqnvCSrOw02lX+3SltWkLkKFq52XrxuMH1zYG",
	"KTpbLn6M4qgQNJpFU5yTaHe1+08AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
