// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ArtifactDeploymentStatus.
const (
	ArtifactDeployed ArtifactDeploymentStatus = "ArtifactDeployed"
	ArtifactFetched  ArtifactDeploymentStatus = "ArtifactFetched"
)

// Valid indicates whether the value is a known member of the ArtifactDeploymentStatus enum.
func (e ArtifactDeploymentStatus) Valid() bool {
	switch e {
	case ArtifactDeployed:
		return true
	case ArtifactFetched:
		return true
	default:
		return false
	}
}

// Defines values for StageVersionStatus.
const (
	DeploymentCreated StageVersionStatus = "DeploymentCreated"
)

// Valid indicates whether the value is a known member of the StageVersionStatus enum.
func (e StageVersionStatus) Valid() bool {
	switch e {
	case DeploymentCreated:
		return true
	default:
		return false
	}
}

// Defines values for VectorDeploymentStatus.
const (
	ArtifactDeploymentCreated VectorDeploymentStatus = "ArtifactDeploymentCreated"
	VectorDownloaded          VectorDeploymentStatus = "VectorDownloaded"
)

// Valid indicates whether the value is a known member of the VectorDeploymentStatus enum.
func (e VectorDeploymentStatus) Valid() bool {
	switch e {
	case ArtifactDeploymentCreated:
		return true
	case VectorDownloaded:
		return true
	default:
		return false
	}
}

// ArtifactDeployment defines model for ArtifactDeployment.
type ArtifactDeployment struct {
	Artifact ArtifactReference `json:"artifact"`

	// Id The artifactDeployment id
	Id ArtifactDeploymentId `json:"id"`

	// LandscapeId The landscape id
	LandscapeId LandscapeId `json:"landscapeId"`
	StageIds    []StageId   `json:"stageIds"`

	// Status The artifactDeployment status
	Status              ArtifactDeploymentStatus `json:"status"`
	VectorDeploymentIds []VectorDeploymentId     `json:"vectorDeploymentIds"`
}

// ArtifactDeploymentStatus The artifactDeployment status
type ArtifactDeploymentStatus string

// ArtifactDeploymentId The artifactDeployment id
type ArtifactDeploymentId = string

// ArtifactDeploymentList defines model for ArtifactDeploymentList.
type ArtifactDeploymentList struct {
	Data []ArtifactDeployment `json:"data"`
}

// ArtifactReference defines model for ArtifactReference.
type ArtifactReference = ComponentReference

// ComponentReference defines model for ComponentReference.
type ComponentReference struct {
	ComponentName    string `json:"componentName"`
	ComponentVersion string `json:"componentVersion"`
	Repository       string `json:"repository"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Identity defines model for Identity.
type Identity struct {
	Email        string              `json:"email"`
	FamilyName   string              `json:"familyName"`
	GivenName    string              `json:"givenName"`
	Name         string              `json:"name"`
	ProjectRoles map[string][]string `json:"projectRoles"`
}

// Landscape defines model for Landscape.
type Landscape struct {
	// Id The landscape id
	Id LandscapeId `json:"id"`

	// Name The name of the landscape
	Name string `json:"name"`
}

// LandscapeId The landscape id
type LandscapeId = string

// LandscapeList defines model for LandscapeList.
type LandscapeList struct {
	Data []Landscape `json:"data"`
}

// Project defines model for Project.
type Project struct {
	// Id The project id
	Id ProjectId `json:"id"`

	// Name The name of the project
	Name string `json:"name"`
}

// ProjectId The project id
type ProjectId = string

// ProjectList defines model for ProjectList.
type ProjectList struct {
	Data []Project `json:"data"`
}

// Session defines model for Session.
type Session struct {
	Id string `json:"id"`
}

// Stage defines model for Stage.
type Stage struct {
	// Id The stage id
	Id StageId `json:"id"`

	// LandscapeId The landscape id
	LandscapeId LandscapeId `json:"landscapeId"`

	// Name The stage name
	Name               string       `json:"name"`
	TargetStageVersion StageVersion `json:"targetStageVersion"`
}

// StageId The stage id
type StageId = string

// StageList defines model for StageList.
type StageList struct {
	Data []Stage `json:"data"`
}

// StageVersion defines model for StageVersion.
type StageVersion struct {
	// Active Indicates if this is the latest active stageVersion
	Active bool `json:"active"`

	// Id The stageVersion id
	Id StageVersionId `json:"id"`

	// StageGeneration Generation of the parent stage
	StageGeneration int                `json:"stageGeneration"`
	Status          StageVersionStatus `json:"status"`

	// Vector StageVersion vector
	Vector string `json:"vector"`
}

// StageVersionStatus defines model for StageVersion.Status.
type StageVersionStatus string

// StageVersionId The stageVersion id
type StageVersionId = string

// VectorDeployment defines model for VectorDeployment.
type VectorDeployment struct {
	// Id The vectorDeployment id
	Id VectorDeploymentId `json:"id"`

	// LandscapeId The landscape id
	LandscapeId LandscapeId `json:"landscapeId"`

	// StageId The stage id
	StageId StageId `json:"stageId"`

	// Status The vectorDeployment status
	Status VectorDeploymentStatus `json:"status"`
	Vector VectorReference        `json:"vector"`
}

// VectorDeploymentStatus The vectorDeployment status
type VectorDeploymentStatus string

// VectorDeploymentId The vectorDeployment id
type VectorDeploymentId = string

// VectorDeploymentList defines model for VectorDeploymentList.
type VectorDeploymentList struct {
	Data []VectorDeployment `json:"data"`
}

// VectorReference defines model for VectorReference.
type VectorReference = ComponentReference

// LandscapeQueryId defines model for LandscapeQueryId.
type LandscapeQueryId = string

// ProjectPathId defines model for ProjectPathId.
type ProjectPathId = string

// VectorDeploymentQueryId defines model for VectorDeploymentQueryId.
type VectorDeploymentQueryId = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// AuthCallbackV1Params defines parameters for AuthCallbackV1.
type AuthCallbackV1Params struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// PostExchangeCodeV1JSONBody defines parameters for PostExchangeCodeV1.
type PostExchangeCodeV1JSONBody struct {
	Code     *string `json:"code,omitempty"`
	Verifier *string `json:"verifier,omitempty"`
}

// LoginV1Params defines parameters for LoginV1.
type LoginV1Params struct {
	// ReturnUrl Fully qualified URL to redirect to after login. The URL must be present in the API server allowlist.
	ReturnUrl string `form:"return_url" json:"return_url"`
}

// ListArtifactDeploymentsV1Params defines parameters for ListArtifactDeploymentsV1.
type ListArtifactDeploymentsV1Params struct {
	// LandscapeId Filter by landscapeId
	LandscapeId *LandscapeQueryId `form:"landscapeId,omitempty" json:"landscapeId,omitempty"`

	// VectorDeploymentId Filter by vectorDeploymentId
	VectorDeploymentId *VectorDeploymentQueryId `form:"vectorDeploymentId,omitempty" json:"vectorDeploymentId,omitempty"`
}

// ListStagesV1Params defines parameters for ListStagesV1.
type ListStagesV1Params struct {
	// LandscapeId Filter by landscapeId
	LandscapeId *LandscapeQueryId `form:"landscapeId,omitempty" json:"landscapeId,omitempty"`
}

// ListVectorDeploymentsV1Params defines parameters for ListVectorDeploymentsV1.
type ListVectorDeploymentsV1Params struct {
	// LandscapeId Filter by landscapeId
	LandscapeId *LandscapeQueryId `form:"landscapeId,omitempty" json:"landscapeId,omitempty"`
}

// PostExchangeCodeV1JSONRequestBody defines body for PostExchangeCodeV1 for application/json ContentType.
type PostExchangeCodeV1JSONRequestBody PostExchangeCodeV1JSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AuthCallbackV1 OIDC callback
	// (GET /v1/auth/callback)
	AuthCallbackV1(w http.ResponseWriter, r *http.Request, params AuthCallbackV1Params)
	// PostExchangeCodeV1 Send temp exchange code and PKCE verifier to get session
	// (POST /v1/exchange)
	PostExchangeCodeV1(w http.ResponseWriter, r *http.Request)
	// GetIdentityV1 Get the current user identity
	// (GET /v1/identity)
	GetIdentityV1(w http.ResponseWriter, r *http.Request)
	// LoginV1 Initiate OIDC login
	// (GET /v1/login)
	LoginV1(w http.ResponseWriter, r *http.Request, params LoginV1Params)
	// LogoutV1 Terminate the current session
	// (POST /v1/logout)
	LogoutV1(w http.ResponseWriter, r *http.Request)
	// ListProjectsV1 List all projects
	// (GET /v1/projects)
	ListProjectsV1(w http.ResponseWriter, r *http.Request)
	// ListArtifactDeploymentsV1 List all artifactDeployments for a project.
	// (GET /v1/projects/{projectId}/artifactDeployments)
	ListArtifactDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListArtifactDeploymentsV1Params)
	// ListLandscapesV1 List all landscapes for a specific project
	// (GET /v1/projects/{projectId}/landscapes)
	ListLandscapesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId)
	// ListStagesV1 List all stages for a project
	// (GET /v1/projects/{projectId}/stages)
	ListStagesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListStagesV1Params)
	// ListVectorDeploymentsV1 List all vectorDeployments for a project
	// (GET /v1/projects/{projectId}/vectorDeployments)
	ListVectorDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListVectorDeploymentsV1Params)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// AuthCallbackV1 OIDC callback
// (GET /v1/auth/callback)
func (_ Unimplemented) AuthCallbackV1(w http.ResponseWriter, r *http.Request, params AuthCallbackV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// PostExchangeCodeV1 Send temp exchange code and PKCE verifier to get session
// (POST /v1/exchange)
func (_ Unimplemented) PostExchangeCodeV1(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetIdentityV1 Get the current user identity
// (GET /v1/identity)
func (_ Unimplemented) GetIdentityV1(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LoginV1 Initiate OIDC login
// (GET /v1/login)
func (_ Unimplemented) LoginV1(w http.ResponseWriter, r *http.Request, params LoginV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LogoutV1 Terminate the current session
// (POST /v1/logout)
func (_ Unimplemented) LogoutV1(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListProjectsV1 List all projects
// (GET /v1/projects)
func (_ Unimplemented) ListProjectsV1(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListArtifactDeploymentsV1 List all artifactDeployments for a project.
// (GET /v1/projects/{projectId}/artifactDeployments)
func (_ Unimplemented) ListArtifactDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListArtifactDeploymentsV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListLandscapesV1 List all landscapes for a specific project
// (GET /v1/projects/{projectId}/landscapes)
func (_ Unimplemented) ListLandscapesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListStagesV1 List all stages for a project
// (GET /v1/projects/{projectId}/stages)
func (_ Unimplemented) ListStagesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListStagesV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListVectorDeploymentsV1 List all vectorDeployments for a project
// (GET /v1/projects/{projectId}/vectorDeployments)
func (_ Unimplemented) ListVectorDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListVectorDeploymentsV1Params) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthCallbackV1 operation middleware
func (siw *ServerInterfaceWrapper) AuthCallbackV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthCallbackV1Params

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthCallbackV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostExchangeCodeV1 operation middleware
func (siw *ServerInterfaceWrapper) PostExchangeCodeV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostExchangeCodeV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIdentityV1 operation middleware
func (siw *ServerInterfaceWrapper) GetIdentityV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIdentityV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginV1 operation middleware
func (siw *ServerInterfaceWrapper) LoginV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginV1Params

	// ------------- Required query parameter "return_url" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "return_url", r.URL.Query(), &params.ReturnUrl, runtime.BindQueryParameterOptions{Type: "string", Format: "uri"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "return_url"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "return_url", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutV1 operation middleware
func (siw *ServerInterfaceWrapper) LogoutV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectsV1 operation middleware
func (siw *ServerInterfaceWrapper) ListProjectsV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectsV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArtifactDeploymentsV1 operation middleware
func (siw *ServerInterfaceWrapper) ListArtifactDeploymentsV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArtifactDeploymentsV1Params

	// ------------- Optional query parameter "landscapeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "landscapeId", r.URL.Query(), &params.LandscapeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "landscapeId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "landscapeId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "vectorDeploymentId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "vectorDeploymentId", r.URL.Query(), &params.VectorDeploymentId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "vectorDeploymentId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vectorDeploymentId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArtifactDeploymentsV1(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLandscapesV1 operation middleware
func (siw *ServerInterfaceWrapper) ListLandscapesV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLandscapesV1(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStagesV1 operation middleware
func (siw *ServerInterfaceWrapper) ListStagesV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStagesV1Params

	// ------------- Optional query parameter "landscapeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "landscapeId", r.URL.Query(), &params.LandscapeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "landscapeId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "landscapeId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStagesV1(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVectorDeploymentsV1 operation middleware
func (siw *ServerInterfaceWrapper) ListVectorDeploymentsV1(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectPathId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVectorDeploymentsV1Params

	// ------------- Optional query parameter "landscapeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "landscapeId", r.URL.Query(), &params.LandscapeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "landscapeId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "landscapeId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVectorDeploymentsV1(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/login", wrapper.LoginV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/auth/callback", wrapper.AuthCallbackV1)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/logout", wrapper.LogoutV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/identity", wrapper.GetIdentityV1)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/exchange", wrapper.PostExchangeCodeV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects", wrapper.ListProjectsV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/landscapes", wrapper.ListLandscapesV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/stages", wrapper.ListStagesV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/vectorDeployments", wrapper.ListVectorDeploymentsV1)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/projects/{projectId}/artifactDeployments", wrapper.ListArtifactDeploymentsV1)
	})

	return r
}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type AuthCallbackV1RequestObject struct {
	Params AuthCallbackV1Params
}

type AuthCallbackV1ResponseObject interface {
	VisitAuthCallbackV1Response(w http.ResponseWriter) error
}

type AuthCallbackV1302ResponseHeaders struct {
	Location  *string
	SetCookie *string
}

type AuthCallbackV1302Response struct {
	Headers AuthCallbackV1302ResponseHeaders
}

func (response AuthCallbackV1302Response) VisitAuthCallbackV1Response(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(302)
	return nil
}

type AuthCallbackV1400JSONResponse struct{ BadRequestJSONResponse }

func (response AuthCallbackV1400JSONResponse) VisitAuthCallbackV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AuthCallbackV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AuthCallbackV1401JSONResponse) VisitAuthCallbackV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthCallbackV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response AuthCallbackV1500JSONResponse) VisitAuthCallbackV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostExchangeCodeV1RequestObject struct {
	Body *PostExchangeCodeV1JSONRequestBody
}

type PostExchangeCodeV1ResponseObject interface {
	VisitPostExchangeCodeV1Response(w http.ResponseWriter) error
}

type PostExchangeCodeV1200JSONResponse Session

func (response PostExchangeCodeV1200JSONResponse) VisitPostExchangeCodeV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostExchangeCodeV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostExchangeCodeV1401JSONResponse) VisitPostExchangeCodeV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PostExchangeCodeV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response PostExchangeCodeV1500JSONResponse) VisitPostExchangeCodeV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetIdentityV1RequestObject struct {
}

type GetIdentityV1ResponseObject interface {
	VisitGetIdentityV1Response(w http.ResponseWriter) error
}

type GetIdentityV1200JSONResponse Identity

func (response GetIdentityV1200JSONResponse) VisitGetIdentityV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetIdentityV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetIdentityV1401JSONResponse) VisitGetIdentityV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetIdentityV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetIdentityV1500JSONResponse) VisitGetIdentityV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LoginV1RequestObject struct {
	Params LoginV1Params
}

type LoginV1ResponseObject interface {
	VisitLoginV1Response(w http.ResponseWriter) error
}

type LoginV1302ResponseHeaders struct {
	Location *string
}

type LoginV1302Response struct {
	Headers LoginV1302ResponseHeaders
}

func (response LoginV1302Response) VisitLoginV1Response(w http.ResponseWriter) error {
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(302)
	return nil
}

type LoginV1400JSONResponse struct{ BadRequestJSONResponse }

func (response LoginV1400JSONResponse) VisitLoginV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LoginV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response LoginV1500JSONResponse) VisitLoginV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutV1RequestObject struct {
}

type LogoutV1ResponseObject interface {
	VisitLogoutV1Response(w http.ResponseWriter) error
}

type LogoutV1200ResponseHeaders struct {
	SetCookie *string
}

type LogoutV1200Response struct {
	Headers LogoutV1200ResponseHeaders
}

func (response LogoutV1200Response) VisitLogoutV1Response(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	return nil
}

type LogoutV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response LogoutV1401JSONResponse) VisitLogoutV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsV1RequestObject struct {
}

type ListProjectsV1ResponseObject interface {
	VisitListProjectsV1Response(w http.ResponseWriter) error
}

type ListProjectsV1200JSONResponse ProjectList

func (response ListProjectsV1200JSONResponse) VisitListProjectsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListProjectsV1401JSONResponse) VisitListProjectsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListProjectsV1500JSONResponse) VisitListProjectsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListArtifactDeploymentsV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
	Params    ListArtifactDeploymentsV1Params
}

type ListArtifactDeploymentsV1ResponseObject interface {
	VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error
}

type ListArtifactDeploymentsV1200JSONResponse ArtifactDeploymentList

func (response ListArtifactDeploymentsV1200JSONResponse) VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListArtifactDeploymentsV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListArtifactDeploymentsV1401JSONResponse) VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListArtifactDeploymentsV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListArtifactDeploymentsV1403JSONResponse) VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListArtifactDeploymentsV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListArtifactDeploymentsV1500JSONResponse) VisitListArtifactDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
}

type ListLandscapesV1ResponseObject interface {
	VisitListLandscapesV1Response(w http.ResponseWriter) error
}

type ListLandscapesV1200JSONResponse LandscapeList

func (response ListLandscapesV1200JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListLandscapesV1401JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListLandscapesV1403JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1404JSONResponse struct{ NotFoundJSONResponse }

func (response ListLandscapesV1404JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListLandscapesV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListLandscapesV1500JSONResponse) VisitListLandscapesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListStagesV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
	Params    ListStagesV1Params
}

type ListStagesV1ResponseObject interface {
	VisitListStagesV1Response(w http.ResponseWriter) error
}

type ListStagesV1200JSONResponse StageList

func (response ListStagesV1200JSONResponse) VisitListStagesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStagesV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListStagesV1401JSONResponse) VisitListStagesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListStagesV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListStagesV1403JSONResponse) VisitListStagesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListStagesV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListStagesV1500JSONResponse) VisitListStagesV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorDeploymentsV1RequestObject struct {
	ProjectId ProjectPathId `json:"projectId"`
	Params    ListVectorDeploymentsV1Params
}

type ListVectorDeploymentsV1ResponseObject interface {
	VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error
}

type ListVectorDeploymentsV1200JSONResponse VectorDeploymentList

func (response ListVectorDeploymentsV1200JSONResponse) VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorDeploymentsV1401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListVectorDeploymentsV1401JSONResponse) VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorDeploymentsV1403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListVectorDeploymentsV1403JSONResponse) VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListVectorDeploymentsV1500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListVectorDeploymentsV1500JSONResponse) VisitListVectorDeploymentsV1Response(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// AuthCallbackV1 OIDC callback
	// (GET /v1/auth/callback)
	AuthCallbackV1(ctx context.Context, request AuthCallbackV1RequestObject) (AuthCallbackV1ResponseObject, error)
	// PostExchangeCodeV1 Send temp exchange code and PKCE verifier to get session
	// (POST /v1/exchange)
	PostExchangeCodeV1(ctx context.Context, request PostExchangeCodeV1RequestObject) (PostExchangeCodeV1ResponseObject, error)
	// GetIdentityV1 Get the current user identity
	// (GET /v1/identity)
	GetIdentityV1(ctx context.Context, request GetIdentityV1RequestObject) (GetIdentityV1ResponseObject, error)
	// LoginV1 Initiate OIDC login
	// (GET /v1/login)
	LoginV1(ctx context.Context, request LoginV1RequestObject) (LoginV1ResponseObject, error)
	// LogoutV1 Terminate the current session
	// (POST /v1/logout)
	LogoutV1(ctx context.Context, request LogoutV1RequestObject) (LogoutV1ResponseObject, error)
	// ListProjectsV1 List all projects
	// (GET /v1/projects)
	ListProjectsV1(ctx context.Context, request ListProjectsV1RequestObject) (ListProjectsV1ResponseObject, error)
	// ListArtifactDeploymentsV1 List all artifactDeployments for a project.
	// (GET /v1/projects/{projectId}/artifactDeployments)
	ListArtifactDeploymentsV1(ctx context.Context, request ListArtifactDeploymentsV1RequestObject) (ListArtifactDeploymentsV1ResponseObject, error)
	// ListLandscapesV1 List all landscapes for a specific project
	// (GET /v1/projects/{projectId}/landscapes)
	ListLandscapesV1(ctx context.Context, request ListLandscapesV1RequestObject) (ListLandscapesV1ResponseObject, error)
	// ListStagesV1 List all stages for a project
	// (GET /v1/projects/{projectId}/stages)
	ListStagesV1(ctx context.Context, request ListStagesV1RequestObject) (ListStagesV1ResponseObject, error)
	// ListVectorDeploymentsV1 List all vectorDeployments for a project
	// (GET /v1/projects/{projectId}/vectorDeployments)
	ListVectorDeploymentsV1(ctx context.Context, request ListVectorDeploymentsV1RequestObject) (ListVectorDeploymentsV1ResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AuthCallbackV1 operation middleware
func (sh *strictHandler) AuthCallbackV1(w http.ResponseWriter, r *http.Request, params AuthCallbackV1Params) {
	var request AuthCallbackV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthCallbackV1(ctx, request.(AuthCallbackV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthCallbackV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthCallbackV1ResponseObject); ok {
		if err := validResponse.VisitAuthCallbackV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostExchangeCodeV1 operation middleware
func (sh *strictHandler) PostExchangeCodeV1(w http.ResponseWriter, r *http.Request) {
	var request PostExchangeCodeV1RequestObject

	var body PostExchangeCodeV1JSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostExchangeCodeV1(ctx, request.(PostExchangeCodeV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostExchangeCodeV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostExchangeCodeV1ResponseObject); ok {
		if err := validResponse.VisitPostExchangeCodeV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIdentityV1 operation middleware
func (sh *strictHandler) GetIdentityV1(w http.ResponseWriter, r *http.Request) {
	var request GetIdentityV1RequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIdentityV1(ctx, request.(GetIdentityV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIdentityV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIdentityV1ResponseObject); ok {
		if err := validResponse.VisitGetIdentityV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginV1 operation middleware
func (sh *strictHandler) LoginV1(w http.ResponseWriter, r *http.Request, params LoginV1Params) {
	var request LoginV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginV1(ctx, request.(LoginV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginV1ResponseObject); ok {
		if err := validResponse.VisitLoginV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutV1 operation middleware
func (sh *strictHandler) LogoutV1(w http.ResponseWriter, r *http.Request) {
	var request LogoutV1RequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutV1(ctx, request.(LogoutV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutV1ResponseObject); ok {
		if err := validResponse.VisitLogoutV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProjectsV1 operation middleware
func (sh *strictHandler) ListProjectsV1(w http.ResponseWriter, r *http.Request) {
	var request ListProjectsV1RequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjectsV1(ctx, request.(ListProjectsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjectsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProjectsV1ResponseObject); ok {
		if err := validResponse.VisitListProjectsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListArtifactDeploymentsV1 operation middleware
func (sh *strictHandler) ListArtifactDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListArtifactDeploymentsV1Params) {
	var request ListArtifactDeploymentsV1RequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListArtifactDeploymentsV1(ctx, request.(ListArtifactDeploymentsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListArtifactDeploymentsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListArtifactDeploymentsV1ResponseObject); ok {
		if err := validResponse.VisitListArtifactDeploymentsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLandscapesV1 operation middleware
func (sh *strictHandler) ListLandscapesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId) {
	var request ListLandscapesV1RequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLandscapesV1(ctx, request.(ListLandscapesV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLandscapesV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLandscapesV1ResponseObject); ok {
		if err := validResponse.VisitListLandscapesV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListStagesV1 operation middleware
func (sh *strictHandler) ListStagesV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListStagesV1Params) {
	var request ListStagesV1RequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListStagesV1(ctx, request.(ListStagesV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStagesV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListStagesV1ResponseObject); ok {
		if err := validResponse.VisitListStagesV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVectorDeploymentsV1 operation middleware
func (sh *strictHandler) ListVectorDeploymentsV1(w http.ResponseWriter, r *http.Request, projectId ProjectPathId, params ListVectorDeploymentsV1Params) {
	var request ListVectorDeploymentsV1RequestObject

	request.ProjectId = projectId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVectorDeploymentsV1(ctx, request.(ListVectorDeploymentsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVectorDeploymentsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVectorDeploymentsV1ResponseObject); ok {
		if err := validResponse.VisitListVectorDeploymentsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FpLc9s4Ev4rKOwedqs4kjPJXnTzyElWFddEaye+eF1bENmUMAEBBgDlaF3671N48A1KlKNkUrnZwqMb",
	"3R++foBPOBZZLjhwrfDsCedEkgw0SPvfNeGJikkO/ylA7haJ+S0BFUuaayo4nuE3lGmQaLVDrJy7SHCE",
	"qRn8bFbhCHOSAZ7h9gwVbyAjZke9y82w0pLyNd7vI7yU4g+I9ZLoTUioH0a1pJzoTS0od+N2WMLngkpI",
	"8EzLAg6LvYNYC3kFORO7DLgeceptZ8ng4YMTh5XZG81VLrgC64nfSHIDnwtQ2vwXC66B2z9JnjMaE6PY",
	"9A9ltHtqbPt3CSme4b9Nay9P3aiavpZSyBsvxIlsn3LBt4TRBEknGNXYmOB9hN8IuaJJAvz7aXQZx6AU",
	"4kIjwph4hMRqsuAaJCfMrv+O2nBUcPiSQ6whQQrkFiQCswqJOC6k9Or9LvQbUfDk+2n2YQOl18D4T4lC",
	"xoAeibNdarSxqn3kpNAbIen/4Tuqd1noDXDtd0flFUVCIgVKmd/gS06d/fblNbH34FJqmpJY1xfJspYU",
	"OUhN3V0hfs4xPcu9biAFCTwGYxGajF3Wusv7qEVvR7a4bkw159NkDYvEKk81ZOrY+lu3wKzNKL8GvtYb",
	"PHsRlTRCpCQ7v7MuVJ/ADEBI7xzIT48w8CLDs/vK3G9AxxswlNU+PST4IeqSVxQgu/Fnu+sT5ZFj7pss",
	"f288GHViTUifhtmjGjKVyepjiZUJJkaJoOfH2taq1bNUf8trqgKYTogmo00YuCT7I0az+x86c31JzA1j",
	"7H2KZ/eH1ZiXPzUu2MM+woHfe+ettvvdhs+nvuWqGXcgFXX81JskIReKaiF34YjfNEFjbtSRH5AWslWb",
	"+HpngjI8dY+ahE+YgVJkDcc1tzvU8/uqdeY7RUInWCSGl/UuoHxGKAuqmZKMst2gn9Z0C3xwlA8N+Bzu",
	"RjBP6klCzQUjbNnSq7oQvR26XHjYJtz5uda2dbDIn7+jV8iEFbf3bUhPDQyldfoEY0aQSJHeQJ159wkm",
	"RI1204OaD7FaJWiAzKoNzsBhtRmfTV2+THiOH5ZVBTHaCx4YX+mDWnBQoBcyYH+/+AzWL033bNvfujxu",
	"yPZHTRTcU3s2PNWbjXTp+UnaMApsHoE8gfRpiMg1aKtCI1IdVbecOwyfbpITEDRoxSF8uaOE0WUXngFb",
	"zo3PR1bHkp3cP9Z0G/DTgiem3ACFqLmuVCGqPHlqU9u6de785eaV8JUQDAgfVx409Wuk92+BgyTaK91W",
	"rh6ryIRIn4+vG6CiXMMaZDuxL1P1OtmbSyD6YGbeV6GptW9qjGOyam73lFHpi4Mpdcdaw6AsdQtjs1s0",
	"PIclwoXHV1d1J5DToWqtW8L0azWvv3jkTJAkUKyNx8ZxMzVS+uPlV2mJNlqGIBHwwziLjIPGGRish7Zn",
	"k1nXmF9ZWxkMQVxIqne3ZqI7m++pzIX4RK0I25+M3b9Vg/JTAvwXP7W2I8npO9i5Jg7lqei74t8fPizR",
	"mmh4JDu0Av0IwNH8ejH9uEAxo0ZrRHhiae2d4ClNjLZofnOlJv+1kqhmRlRj8HK5sGDxJI+3L4yxRA6c",
	"5BTP8MvJxeSlScaJ3tgjTrcvpqTQm2lMGFuR+JP5cQ26r+4NxEC34Mi/bH457jVlFEqlyOzY4mqJSKpB",
	"IlXYtmNaMMTEmvIJev0l3hC+9ru4dUIiLT4Bd6cFpcmKUbUBhUjV1XI2d8c26LNyDb5tS2zudb97YY9W",
	"N+Lvn4ItZV/2ndDhDu9j7uJpGz10utMvL34NWTqh0iSrWjhj1w3FvmFJqyU4wRHeAEnKZwgRD0TOSkYh",
	"2ZE3hVvQv9RXoL3NXHBNKHfuLJ21uJocbtHvI/zq4mKILCoDTRu9e7vkxfElrb7sPsL/GiOn3QZvkgGe",
	"3T9EWBVZRuQOz/D7xdUcVVfFpI5rAzNshGJLI+ZCgUe5ZUuhApfpjjCa2KzK3gED/C1ImlKQ9h8JupBc",
	"VSalKbJPCpMe/pdC6fJWzUUC9g74FvZvItmd1Jwe2V8pVQ3jpdsu2HcvSPeJ5lfno7O00MvyKdA8f//u",
	"R0HRLRhahyxHJVJqGCzfzV/XWNACrUGjRnQJAo42uk8D5O3wVE5EMSM0U458PZ97FrEvMlZcH2xvQZeN",
	"Lo+zb+TGqp32Y/ix8txb0C5yFdLWGYUCWRl10D02+B3wjaNiR6IrKR6V83wVTFvBFniSC8p1hFawppxT",
	"vrYzLXDMVJQy8ThB7/lwmKi2lpVsQ2hG6JTktJcUhALvtTlUKOJ2XnwLxnboc0GYQXSCPt5cGzGyEeNc",
	"TPMZgklQzZysUBqtAOUSlM1RndKXy0X5YGgfMhlVejLwcuxI9H8uwg3H6FTIjGg8w4WkgdLt5JA97LLz",
	"R+dnhtIz89mCU02JBmTDo0P7gbsgCj0cGecMiGznEz75QzfOhSZPrNoOQ0x1bcUMklSnhveCNMiMckeB",
	"1dVhu47bDuVDN5CJMkfuqD/CjyczWoubPpTatxjqWOjwjVF1NHQQxlD5/Uj5MK7Qliq6YlClqq04Ytgx",
	"4BqqtN9Ifdso0mzr/mCBxOhkTVrZv3ZQ9VPPSdOn6gud/bT/VDrOiYF1DYeajICUWk3QnHDDwqn9bgeS",
	"1vdKSMheLyHs7n47RYUiR8ic9ZRp++MmU5QdWdD7CmvEmqFPmXpx4JxAHXjMPi9mX128PL6o/jbprCgP",
	"Ya6NtNPxX+FwHOxr2A6BPQjdCkNnQOy3hFD7CfGvRs6ri1fHV1Sfd50VajUsvHtVDjFNadx8aDwNabYN",
	"Ow5l7h3oWXQaxp/tcv9FbPkt8Vo/iv08LOdw0vb56WjrhtRxwOutOicIu0HxJ8Rj8LXj54FmHx5jUNqu",
	"+XoPIvcPxiWuHA/V/rcdMvyHf5iAxNTx/8QRNvXtDE9JTvH+Yf9nAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
