// Code generated by MockGen. DO NOT EDIT.
// Source: vector.go
//
// Generated by this command:
//
//	mockgen -source=vector.go -destination=mocks/mock_ocm_port.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/konfidence-project/gcp-vector-assembly-controller/internal/controller/domain"
	gomock "go.uber.org/mock/gomock"
	compref "ocm.software/open-component-model/bindings/go/oci/compref"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// MockVectorOcmPort is a mock of VectorOcmPort interface.
type MockVectorOcmPort struct {
	ctrl     *gomock.Controller
	recorder *MockVectorOcmPortMockRecorder
	isgomock struct{}
}

// MockVectorOcmPortMockRecorder is the mock recorder for MockVectorOcmPort.
type MockVectorOcmPortMockRecorder struct {
	mock *MockVectorOcmPort
}

// NewMockVectorOcmPort creates a new mock instance.
func NewMockVectorOcmPort(ctrl *gomock.Controller) *MockVectorOcmPort {
	mock := &MockVectorOcmPort{ctrl: ctrl}
	mock.recorder = &MockVectorOcmPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorOcmPort) EXPECT() *MockVectorOcmPortMockRecorder {
	return m.recorder
}

// CreateVector mocks base method.
func (m *MockVectorOcmPort) CreateVector(ctx context.Context, repoSpec runtime.Typed, vector domain.Vector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVector", ctx, repoSpec, vector)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVector indicates an expected call of CreateVector.
func (mr *MockVectorOcmPortMockRecorder) CreateVector(ctx, repoSpec, vector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVector", reflect.TypeOf((*MockVectorOcmPort)(nil).CreateVector), ctx, repoSpec, vector)
}

// GetLatestArtifactVersions mocks base method.
func (m *MockVectorOcmPort) GetLatestArtifactVersions(ctx context.Context, references []compref.Ref) ([]domain.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestArtifactVersions", ctx, references)
	ret0, _ := ret[0].([]domain.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestArtifactVersions indicates an expected call of GetLatestArtifactVersions.
func (mr *MockVectorOcmPortMockRecorder) GetLatestArtifactVersions(ctx, references any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestArtifactVersions", reflect.TypeOf((*MockVectorOcmPort)(nil).GetLatestArtifactVersions), ctx, references)
}

// GetLatestVector mocks base method.
func (m *MockVectorOcmPort) GetLatestVector(ctx context.Context, vectorRef compref.Ref) (domain.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVector", ctx, vectorRef)
	ret0, _ := ret[0].(domain.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVector indicates an expected call of GetLatestVector.
func (mr *MockVectorOcmPortMockRecorder) GetLatestVector(ctx, vectorRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVector", reflect.TypeOf((*MockVectorOcmPort)(nil).GetLatestVector), ctx, vectorRef)
}
