apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/stage-api-resource-schema.yml
- ./resources/stageconfiguration-api-resource-schema.yml
- ./resources/stageconfiguration-api-export.yml
- ./resources/gcp-workspace-type.yml
- ./resources/workspaces.yml

