apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/stageconfiguration-api-resource-schema.yml
- ./resources/stageconfiguration-api-export.yml
- ./resources/stageconfiguration-api-binding.yml
- ./resources/stagesync-api-resource-schema.yml
- ./resources/stagesync-api-export.yml
- ./resources/stagesync-api-binding.yml
