// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/konfidence-project/konfidence/internal/galaxy/vectorassembly/assembly (interfaces: VectorRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_vector_repository.go -package=mocks github.com/konfidence-project/konfidence/internal/galaxy/vectorassembly/assembly VectorRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vector "github.com/konfidence-project/konfidence/internal/galaxy/vectorassembly/vector"
	gomock "go.uber.org/mock/gomock"
	compref "ocm.software/open-component-model/bindings/go/oci/compref"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// MockVectorRepository is a mock of VectorRepository interface.
type MockVectorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVectorRepositoryMockRecorder
	isgomock struct{}
}

// MockVectorRepositoryMockRecorder is the mock recorder for MockVectorRepository.
type MockVectorRepositoryMockRecorder struct {
	mock *MockVectorRepository
}

// NewMockVectorRepository creates a new mock instance.
func NewMockVectorRepository(ctrl *gomock.Controller) *MockVectorRepository {
	mock := &MockVectorRepository{ctrl: ctrl}
	mock.recorder = &MockVectorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorRepository) EXPECT() *MockVectorRepositoryMockRecorder {
	return m.recorder
}

// CreateVector mocks base method.
func (m *MockVectorRepository) CreateVector(ctx context.Context, repoSpec runtime.Typed, v vector.Vector, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVector", ctx, repoSpec, v, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVector indicates an expected call of CreateVector.
func (mr *MockVectorRepositoryMockRecorder) CreateVector(ctx, repoSpec, v, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVector", reflect.TypeOf((*MockVectorRepository)(nil).CreateVector), ctx, repoSpec, v, alias)
}

// GetArtifacts mocks base method.
func (m *MockVectorRepository) GetArtifacts(ctx context.Context, references []compref.Ref) ([]vector.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifacts", ctx, references)
	ret0, _ := ret[0].([]vector.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifacts indicates an expected call of GetArtifacts.
func (mr *MockVectorRepositoryMockRecorder) GetArtifacts(ctx, references any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifacts", reflect.TypeOf((*MockVectorRepository)(nil).GetArtifacts), ctx, references)
}

// GetVector mocks base method.
func (m *MockVectorRepository) GetVector(ctx context.Context, vectorRef compref.Ref) (vector.Vector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVector", ctx, vectorRef)
	ret0, _ := ret[0].(vector.Vector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVector indicates an expected call of GetVector.
func (mr *MockVectorRepositoryMockRecorder) GetVector(ctx, vectorRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVector", reflect.TypeOf((*MockVectorRepository)(nil).GetVector), ctx, vectorRef)
}
