apiVersion: apps/v1
kind: Deployment
metadata:
  name: landscape-vector-deployment-controller
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: landscape-vector-deployment-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: landscape-vector-deployment-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: landscape-vector-deployment-controller
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
      - command:
          - sh
          - -c
          - |
            cp /etc/ssl/certs/extra/ca.crt /usr/local/share/ca-certificates/ca.crt
            update-ca-certificates
            /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: konfidence-project/landscape-vector-deployment-controller:latest
        imagePullPolicy: Always
        name: manager
        ports: []
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          runAsNonRoot: false
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
          - name: ca-tls
            mountPath: /etc/ssl/certs/extra
      volumes:
        - name: ca-tls
          secret:
            secretName: ca-tls-secret
      serviceAccountName: landscape-vector-deployment-controller
      terminationGracePeriodSeconds: 10
