// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID                pgtype.UUID
	Subject           string
	Name              *string
	GivenName         *string
	FamilyName        *string
	PreferredUserName *string
	Email             *string
	Roles             []string
	Groups            []string
	AccessToken       string
	RefreshToken      *string
	Expiry            int64
	CreatedAt         pgtype.Timestamptz
}
