// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error)
	DeleteExpiredSessions(ctx context.Context, expiredBefore pgtype.Timestamptz) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetAndTouchSession(ctx context.Context, arg GetAndTouchSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
