// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (subject, name, given_name, family_name, preferred_user_name, email, groups, access_token, refresh_token, expiry)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type CreateSessionParams struct {
	Subject           string
	Name              *string
	GivenName         *string
	FamilyName        *string
	PreferredUserName *string
	Email             *string
	Groups            []string
	AccessToken       string
	RefreshToken      *string
	Expiry            int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Subject,
		arg.Name,
		arg.GivenName,
		arg.FamilyName,
		arg.PreferredUserName,
		arg.Email,
		arg.Groups,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expiry,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, subject, name, given_name, family_name, preferred_user_name, email, groups, access_token, refresh_token, expiry, created_at FROM session
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Name,
		&i.GivenName,
		&i.FamilyName,
		&i.PreferredUserName,
		&i.Email,
		&i.Groups,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}
