# Shared Makefile for all modules
# Include this file in module-specific Makefiles

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec

# Default module name (can be overridden in module Makefile)
MODULE_NAME ?= $(notdir $(CURDIR))

# Tool Binaries - shared in root directory
REPO_ROOT := $(shell git rev-parse --show-toplevel)
LOCALBIN ?= $(REPO_ROOT)/.bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen
GOLANGCI_LINT = $(LOCALBIN)/golangci-lint
KUSTOMIZE ?= $(LOCALBIN)/kustomize

# Tool Versions
CONTROLLER_TOOLS_VERSION ?= v0.16.4
GOLANGCI_LINT_VERSION ?= v2.4.0
KUSTOMIZE_VERSION ?= v5.6.0

.PHONY: all
all: manifests generate fmt vet lint docs

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: manifests
manifests: controller-gen kustomize ## Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
	@echo "Generating manifests for module $(MODULE_NAME)..."

	@echo "  Generating CRDs..."
	@mkdir -p "config/bases/crd" "config/release"
	@$(CONTROLLER_GEN) crd paths="./..." output:crd:artifacts:config="./config/bases/crd"
	@echo "  Generating kustomization.yaml..."
	@{ \
		echo "# Code generated by make manifests. DO NOT EDIT."; \
		echo "resources:"; \
		find "config/bases/crd" -type f -name '*.yaml' | sort | sed -E 's|^config/bases/| - ./|'; \
	} > "config/bases/kustomization.yaml"
	@echo "  Building release bundle..."
	@$(KUSTOMIZE) build "config/bases" > "config/release/install.yaml"

.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="$(REPO_ROOT)/hack/boilerplate.go.txt" paths="./..."

.PHONY: fmt
fmt: ## Run go fmt against code.
	go fmt ./...

.PHONY: vet
vet: ## Run go vet against code.
	go vet ./...

.PHONY: lint
lint: golangci-lint ## Run golangci-lint linter
	$(GOLANGCI_LINT) run

.PHONY: lint-fix
lint-fix: golangci-lint ## Run golangci-lint linter and perform fixes
	$(GOLANGCI_LINT) run --fix

.PHONY: docs
docs: ## Generate CRD reference documentation for all API versions
	@echo "Generating CRD documentation for module $(MODULE_NAME)..."
	@command -v crd-ref-docs >/dev/null 2>&1 || { \
		echo "crd-ref-docs is required but not installed."; \
		echo "Install with: go install github.com/elastic/crd-ref-docs@latest"; \
		exit 1; \
	}
	@mkdir -p "docs"
	@crd-ref-docs \
		--source-path="." \
		--config="$(REPO_ROOT)/.crd-ref-docs.config.yaml" \
		--output-path="./docs" \
		--output-mode=group \
		--renderer=markdown;
	@if [ -f "./docs/$(MODULE_NAME).konfidence.cloud.md" ]; then \
		mv "./docs/$(MODULE_NAME).konfidence.cloud.md" "./docs/README.md"; \
	fi

##@ Build

.PHONY: build
build: manifests generate fmt vet ## Build module
	go build -v ./...

##@ Dependencies

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary.
$(CONTROLLER_GEN): $(LOCALBIN)
	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))

.PHONY: kustomize
kustomize: $(KUSTOMIZE) ## Download kustomize locally if necessary.
$(KUSTOMIZE): $(LOCALBIN)
	$(call go-install-tool,$(KUSTOMIZE),sigs.k8s.io/kustomize/kustomize/v5,$(KUSTOMIZE_VERSION))

.PHONY: golangci-lint
golangci-lint: $(GOLANGCI_LINT) ## Download golangci-lint locally if necessary.
$(GOLANGCI_LINT): $(LOCALBIN)
	@[ -f "$(GOLANGCI_LINT)-$(GOLANGCI_LINT_VERSION)" ] || { \
	set -e; \
	OS=$$(uname -s | tr '[:upper:]' '[:lower:]'); \
	ARCH=$$(uname -m); \
	case $$ARCH in \
		x86_64) ARCH="amd64" ;; \
		arm64|aarch64) ARCH="arm64" ;; \
		*) echo "Unsupported architecture: $$ARCH"; exit 1 ;; \
	esac; \
	VERSION=$$(echo "$(GOLANGCI_LINT_VERSION)" | sed 's/^v//'); \
	ARCHIVE_NAME="golangci-lint-$$VERSION-$$OS-$$ARCH.tar.gz"; \
	DOWNLOAD_URL="https://github.com/golangci/golangci-lint/releases/download/$(GOLANGCI_LINT_VERSION)/$$ARCHIVE_NAME"; \
	echo "Downloading $$ARCHIVE_NAME from golangci/golangci-lint $(GOLANGCI_LINT_VERSION)..."; \
	curl -sSL "$$DOWNLOAD_URL" | tar -xz -C $(LOCALBIN) "golangci-lint-$$VERSION-$$OS-$$ARCH/golangci-lint"; \
	mv "$(LOCALBIN)/golangci-lint-$$VERSION-$$OS-$$ARCH/golangci-lint" "$(GOLANGCI_LINT)-$(GOLANGCI_LINT_VERSION)"; \
	rm -rf "$(LOCALBIN)/golangci-lint-$$VERSION-$$OS-$$ARCH"; \
	chmod +x "$(GOLANGCI_LINT)-$(GOLANGCI_LINT_VERSION)"; \
	} ;\
	ln -sf $(GOLANGCI_LINT)-$(GOLANGCI_LINT_VERSION) $(GOLANGCI_LINT)

# go-install-tool will 'go install' any package with custom target and name of binary, if it doesn't exist
# $1 - target path with name of binary
# $2 - package url which can be installed
# $3 - specific version of package
define go-install-tool
@[ -f "$(1)-$(3)" ] || { \
set -e; \
package=$(2)@$(3) ;\
echo "Downloading $${package}" ;\
rm -f $(1) || true ;\
GOBIN=$(LOCALBIN) go install $${package} ;\
mv $(1) $(1)-$(3) ;\
} ;\
ln -sf $(1)-$(3) $(1)
endef
