package docs

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/konfidence-project/konfidence/internal/kden/log"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func NewDocsCmd() *cobra.Command {
	var docType string
	var dir string
	var frontmatter bool

	docsCmd := &cobra.Command{
		Use:   "docs",
		Short: "Generate documentation as markdown or man pages",
		Long: `Generate documentation files for kden.

Supported types:
  markdown  Single merged Markdown file (default)
  man       groff man pages, one per command

Examples:
  kden docs --type markdown --dir api/docs/
  kden docs --type man --dir ./man/`,
		Hidden: true,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := os.MkdirAll(dir, 0755); err != nil {
				return fmt.Errorf("failed to create output directory: %w", err)
			}
			switch docType {
			case "markdown":
				path := dir + "/cli.md"
				f, err := os.Create(path)
				if err != nil {
					return fmt.Errorf("failed to create output file: %w", err)
				}
				if frontmatter {
					if err := writeCLIFrontmatter(f); err != nil {
						err := errors.Join(f.Close(), err)
						return fmt.Errorf("failed to write frontmatter: %w", err)
					}
				}
				if err := genMarkdownAll(cmd.Root(), f); err != nil {
					err := errors.Join(f.Close(), err)
					return fmt.Errorf("failed to generate markdown docs: %w", err)
				}
				if err := f.Close(); err != nil {
					return fmt.Errorf("failed to write %s: %w", path, err)
				}
				log.Infof("CLI reference generated at %s", path)
			case "man":
				header := &doc.GenManHeader{
					Title:   "KDEN",
					Section: "1",
					Source:  "kden",
					Manual:  "User Commands",
				}
				if err := doc.GenManTree(cmd.Root(), header, dir); err != nil {
					return fmt.Errorf("failed to generate man pages: %w", err)
				}
				log.Infof("Man pages generated in %s", dir)
			default:
				return fmt.Errorf("unknown type %q: use markdown or man", docType)
			}
			return nil
		},
	}

	docsCmd.Flags().StringVar(&docType, "type", "markdown", "output type: markdown or man")
	docsCmd.Flags().StringVar(&dir, "dir", "./", "output directory")
	docsCmd.Flags().BoolVar(&frontmatter, "frontmatter", false, "prepend VitePress frontmatter to the markdown output")

	if err := docsCmd.RegisterFlagCompletionFunc("type", func(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) { //nolint:errcheck
		return []string{"markdown", "man"}, cobra.ShellCompDirectiveNoFileComp
	}); err != nil {
		panic(err)
	}

	return docsCmd
}

// writeCLIFrontmatter emits the VitePress frontmatter and top-level heading so
// the docs site links and titles cli.md the same way it does crd.md.
func writeCLIFrontmatter(w io.Writer) error {
	const frontmatter = `---
title: CLI
description: Konfidence command-line interface reference and command documentation.
outline: [2, 3]
editLink: true
lastUpdated: true
---

`
	_, err := io.WriteString(w, frontmatter)
	return err
}

// genMarkdownAll recursively writes all commands into a single Markdown document.
// Cross-reference links are rewritten to intra-page anchors.
func genMarkdownAll(cmd *cobra.Command, w io.Writer) error {
	var buf bytes.Buffer
	if err := doc.GenMarkdownCustom(cmd, &buf, func(s string) string {
		s = strings.TrimSuffix(s, ".md")
		return "#" + strings.ToLower(strings.ReplaceAll(s, "_", "-"))
	}); err != nil {
		return err
	}
	// Strip HR separators and the "Auto generated by spf13/cobra" footer lines.
	var out strings.Builder
	scanner := bufio.NewScanner(&buf)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "---" || strings.HasPrefix(line, "###### Auto generated by spf13/cobra") {
			out.WriteString("\n")
			continue
		}
		// cobra puts a tab between the SEE ALSO link and its description — replace with a space.
		out.WriteString(strings.ReplaceAll(line, "\t", " "))
		out.WriteString("\n")
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	if _, err := io.WriteString(w, out.String()); err != nil {
		return err
	}
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := genMarkdownAll(c, w); err != nil {
			return err
		}
	}
	return nil
}
