apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: galaxy-stage-configuration-controller
    app.kubernetes.io/managed-by: kustomize
  name: galaxy-stage-configuration-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: galaxy-stage-configuration-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: galaxy-stage-configuration-controller
