---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: galaxy-stage-configuration-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galaxy.konfidence.cloud
  resources:
  - stageconfigurations
  - stagesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - galaxy.konfidence.cloud
  resources:
  - stageconfigurations/status
  - stagesyncs/status
  verbs:
  - get
  - patch
  - update
