---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcp-stage-configuration-manager
rules:
- apiGroups:
  - common.konfidence.cloud
  resources:
  - stages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - common.konfidence.cloud
  resources:
  - stages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - global.konfidence.cloud
  resources:
  - stageconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - global.konfidence.cloud
  resources:
  - stageconfigurations/status
  verbs:
  - get
  - patch
  - update
