// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/konfidence-project/konfidence/pkg/ocm/crypto (interfaces: Digester)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_digester.go -package=mocks github.com/konfidence-project/konfidence/pkg/ocm/crypto Digester
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	crypto "crypto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	runtime "ocm.software/open-component-model/bindings/go/descriptor/runtime"
)

// MockDigester is a mock of Digester interface.
type MockDigester struct {
	ctrl     *gomock.Controller
	recorder *MockDigesterMockRecorder
	isgomock struct{}
}

// MockDigesterMockRecorder is the mock recorder for MockDigester.
type MockDigesterMockRecorder struct {
	mock *MockDigester
}

// NewMockDigester creates a new mock instance.
func NewMockDigester(ctrl *gomock.Controller) *MockDigester {
	mock := &MockDigester{ctrl: ctrl}
	mock.recorder = &MockDigesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDigester) EXPECT() *MockDigesterMockRecorder {
	return m.recorder
}

// GenerateDigest mocks base method.
func (m *MockDigester) GenerateDigest(ctx context.Context, desc *runtime.Descriptor) (*runtime.Digest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDigest", ctx, desc)
	ret0, _ := ret[0].(*runtime.Digest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDigest indicates an expected call of GenerateDigest.
func (mr *MockDigesterMockRecorder) GenerateDigest(ctx, desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDigest", reflect.TypeOf((*MockDigester)(nil).GenerateDigest), ctx, desc)
}

// GetHashAlgorithm mocks base method.
func (m *MockDigester) GetHashAlgorithm() crypto.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHashAlgorithm")
	ret0, _ := ret[0].(crypto.Hash)
	return ret0
}

// GetHashAlgorithm indicates an expected call of GetHashAlgorithm.
func (mr *MockDigesterMockRecorder) GetHashAlgorithm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHashAlgorithm", reflect.TypeOf((*MockDigester)(nil).GetHashAlgorithm))
}

// GetNormalisationAlgorithm mocks base method.
func (m *MockDigester) GetNormalisationAlgorithm() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNormalisationAlgorithm")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNormalisationAlgorithm indicates an expected call of GetNormalisationAlgorithm.
func (mr *MockDigesterMockRecorder) GetNormalisationAlgorithm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNormalisationAlgorithm", reflect.TypeOf((*MockDigester)(nil).GetNormalisationAlgorithm))
}
