---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - artifactdeployments
  - stageversions
  - stageversionusages
  - taskexecutions
  - vectordeployments
  - vectormigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - artifactdeployments/status
  - stageversions/status
  - stageversionusages/status
  - taskexecutions/status
  - vectordeployments/status
  - vectormigrations/status
  verbs:
  - get
  - patch
  - update
