apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gcp-vector-promotion-controller
    app.kubernetes.io/managed-by: kustomize
  name: gcp-vector-promotion-controller-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gcp-vector-promotion-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: gcp-vector-promotion-controller
