apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: galaxy-vector-promotion-controller
    app.kubernetes.io/managed-by: kustomize
  name: galaxy-vector-promotion-controller
