# permissions for end users to view vectordeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: landscape-vectordeployment-viewer-role
rules:
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - vectordeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - vectordeployments/status
  verbs:
  - get
