# This rule is not used by the project crds itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the landscape.konfidence.cloud.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: crds
    app.kubernetes.io/managed-by: kustomize
  name: landscape-taskexecution-editor-role
rules:
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - taskexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - landscape.konfidence.cloud
  resources:
  - taskexecutions/status
  verbs:
  - get
