apiVersion: global.konfidence.cloud/v1alpha1
kind: VectorTemplate
metadata:
  namespace: default
  name: shopping-app-latest
spec:
  name: vector
  base: https://registry.kdenv.lab/sample-project//konfidence-project/sample-vector
  uploadTarget: https://registry.kdenv.lab/sample-project//konfidence-project/constructed-vector
  components:
    - https://registry.kdenv.lab/sample-project//konfidence-project/sample-vector/service1
    - https://registry.dwc.com/sample-project//dwc.tools.sap/dwc-project/dev/service2
    - https://registry.example.lab/sample-project//dwc.tools.sap/dwc-project/dev/service3
