services:
  zot:
    image: ghcr.io/project-zot/zot-linux-arm64:latest
    container_name: zot-registry
    ports:
      - "5100:5100"
    volumes:
      - ./zot-data:/var/lib/registry
      - ./htpasswd:/etc/zot/htpasswd:ro  # user: "user", password: "password"
      - ./zot-config.json:/etc/zot/config.json
    restart: unless-stopped