name: kden CLI
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: konfidence-large
    steps:
      - name: Prepare sourcecode
        uses: konfidence-project/.github/.github/actions/prepare-sourcecode@v4
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.KONFIDENCE_PROJECT_REPO_ACCESS_PRIVATE_KEY }}

      - name: Build
        run: |
          go mod tidy
          make build-kden-cli
